### ISSUE TITLE
[BUG] You can fly down into closed constructions (from a skybox map)

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#100]
**Describe the bug**
If you use the Soar up feature of the Fly skill on maps that it is allowed, you can enter other players constructions (after soaring down). Most of the time, the player ends up *inside* the door of the construction. 

If there is no door, the player simply appears inside it (sometimes this happens even when there is a door). Also, there *seems* to be some sort of measure agaisnt this where the player is 'pushed' off to a non-enclosed space, but it does not work most of the time.

**To Reproduce**
1. Construct or find a closed room (walled with roofs)
2. Soar up to the Skybox map
3. Go, in the skybox, where the building interior would be (no solid object in it)
4. Soar down and enter it, either exactly on that spot or on a door.

**Expected behavior**
A player should be unable to soar down into enclosed spaces by crossing Z-Levels with Fly.

**Screenshots**
Here is a gif of a player using the bug to enter a closed building (with added Coordinates from Sense).
![BOrcdyIgGe](https://user-images.githubusercontent.com/81521485/113172207-96b43a00-921e-11eb-8d25-fd22a50753b6.gif)

**Byond Details:**
Any.

**First identifiable version:**
The bug was discovered in the 'Dragon Universe Classic r20210304' version.

**Comment by Khunkurisu** [comment]
This, among other issues with the Soar system should be resolved in an upcoming update.  If it is not, feel free to reopen this issue or make another detailing the new/continuing problem(s).
