### ISSUE TITLE
[Suggestion] Add a cooldown for the Soar up/down ability of the Fly skill during fights

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#102]
**Is your feature request related to a problem? Please describe.**
Sort of. You can abuse the Soar ability while in combat to quickly change Z-Levels.

**Describe the solution you'd like**
A short cooldown (maybe 5 or 10 seconds?) for the Soar ability if you have been recently damaged.

**Describe alternatives you've considered**
Maybe an increasced Energy cost to use the Soar ability even if were not damaged would also be good enought.

**Additional context**
N/A.

**Comment by Khunkurisu** [comment]
I'll play around with increasing the energy cost and a cooldown.  That said, it's already a pretty hefty energy cost as it stands so I probably won't change that aspect very much.

**Comment by Khunkurisu** [comment]
For now, the cost to increase your elevation is tripled if your health is below 70%.  Will tweak the values if necessary.
