### ISSUE TITLE
[BUG] Game gets terribly laggy on certain tabs of the chat UI

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#106]
**Describe the bug**
This is *probably* an old and well known issue.

The entire game gets super laggy for a player if they are on the Stats, Items or Sense tab. If that player is on the Other or Skills tab, the game runs (almost) normally. 

Those three tabs are the only ones that seem to make the game laggy. Also, if the player has Sense 3 and he Senses someone, that 'sensing-other' tab will too be somewhat laggy. 

From what **I** can **infer**, the tabs that constantly update anything are the ones that generate the most lag. A sense tab with no one on it will not be laggy at all but one with, say, ten or more players will.

Likewise, a Sensing-someone tab with sense 2 will generate little interference on gameplay since it has few things to update. 

Even hiding the UI with the F6 hotkey won't reduce that lag (in fact, it *seems* to be even laggier for some reason).

**To Reproduce**
1. Click on any of the aforementioned tabs.
2. Try to play and see a significantly laggier game experience.

**Expected behavior**
The UI should not affect a player's performance so much.

**Screenshots**
N/A. 

**Byond Details:**
Any.

**First identifiable version:**
The version the bug was detected was the March 4th, 2021 (2021-03-04) release, named "Dragon Universe Classic r20210304".

**Comment by Khunkurisu** [comment]
While this is certainly an annoying issue, it is not one that can be fixed without being rid of the tabs entirely.  The reason being is that it isn't actually a bug in the game, but a problem with the engine itself.  The tabs get updated at a regular interval, so tabs containing objects or characters cause a great deal of lag for the player viewing them.

The only real fix for this is to not use the tabs at all, which is a goal in the long-term but not something we can do until we have a functioning HUD.
