### ISSUE TITLE
[BUG] A player can lose the ability to move and use skills if he gets pushed while charging a Death Ball-like skill

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#107]
**Describe the bug**
See title. This is very similar to issue #63 (shockwave in genki-dama skill stucks character), but it happens based on something else. My best *guess* is that being pushed away from the skill can sometimes cause this bug to happen.

If a player is in the process of charging, say, a Death Ball, he can get stuck permanently doing that if he gets pushed away from the skill (the ball itself) and then the skill is destroyed.

I've had this happen to me a few times and being pushed away from the skill was the only thing related to losing movement. It didn't happen by shockwave; I was simply *punched* away from it and then suddenly could not move or use any skill.

I could not release the skill or create another only, the only thing I could do was chatting, fly up and down (not soar) and *face* different directions. 

It may also be something else other than being pushed away. Say, for example, the skill getting destroyed by a punch (it did happen once) or some other means. Not once this bug happened to me because of a Shockwave so it should not be it, really.

It may also be getting moved away from it and then it getting destroyed at the same time. For example, someone Lunges at a player and for unknown reasons the death ball is destroyed at the same time that a target gets launched away (can't really remember if this happened to me).

**To Reproduce**
(can't really describle this one since its only a guess)
1. Charge a Death-ball-like skill.
2. Try to get pushed away from it (and not being able to control it)
3. Get stuck.

**Expected behavior**
A player should not be unable to do anything after getting pushed away from a Death Ball-like skill.

**Screenshots**
N/A. (can't get to reproduce it, may update if it does happen again)

**Byond Details:**
Any.

**First identifiable version:**
The version the bug was detected was the March 4th, 2021 (2021-03-04) release, named "Dragon Universe Classic r20210304".

**Comment by Khunkurisu** [comment]
Players should no longer be able to get knocked out of charging such attacks, thus resolving this issue.
