### ISSUE TITLE
[Suggestion] Allow Player-descriptions to directly show images

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#108]
**Is your feature request related to a problem? Please describe.**
It isn't related to problem, just an inconvenience.

**Describe the solution you'd like**
I'd like for players to be able to attach images to player descriptions by linking them. For example, I add a link to 'www.imagebank/character_appearence.png' and it shows directly on the game. I don't really know if this is possible but the game chat seems to be HTML-based so it should be.

This could also be added to the admin-tools Narrate and Message, if possible.

**Describe alternatives you've considered**
Not any, really. Maybe toggleable dropboxes with the link and that would show the image if you click on it.

**Additional context**
It would be a nice feature for RP purposes.

**Comment by Khunkurisu** [comment]
Added in 35.5.15
