### ISSUE TITLE
[BUG] DeadZone Amulet shows negative cooldown

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#109]
**Describe the bug**
See title. When an amulet is used, the cooldown timer shown in chat goes into negative numbers after 3 or so seconds. Adding to that, those numbers are completely inconsistent in their growth.

**To Reproduce**
1. Use a DeadZone Amulet.
2. Try to use it again.
3. See negative numbers in the cooldown 

**Expected behavior**
The amulet should show the proper cooldown timer instead of negative numbers.

**Screenshots**
Chat screenshot showing how the cooldown behaves:
![image](https://user-images.githubusercontent.com/81521485/113417152-34337900-9399-11eb-9e34-c03ee0580009.png)
And no, I didn't wait 400 seconds. It was somewhere around ~25 seconds.

Screenshot of an amulet being spammed (~3 uses per second):
![image](https://user-images.githubusercontent.com/81521485/113417371-9ee4b480-9399-11eb-87fc-09e8831ba160.png)

**Byond Details:**
Any.

**First identifiable version:**
Pretty sure this is 5+ years old. At least, it isn't from any version after 2018.

**Comment by Khunkurisu** [comment]
Proper cooldown now appears.
