### ISSUE TITLE
[BUG] You can spam-call the Mate verb on someone else

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#110]
**Describe the bug**
See title. You can spam the skill Mate on someone else and they will be plagued with notifications windows for accepting/declining the request.

**To Reproduce**
1. Use the mate skill on someone else repeatedly.
2. See that almost every use of the skill creates a new window.

**Expected behavior**
You should not be aple to spam Mate. A cooldown of five seconds or so should be enough to prevent the skill from being abused. And maybe an option to disable Mate requests on the Options menu, since that would pretty much remove the entire problem.

**Screenshots**
Screenshot from the skill getting spam-used on a player:
![ddVAktBxHf](https://user-images.githubusercontent.com/81521485/113464106-b60abd00-9400-11eb-9080-736d654f9af8.gif)

**Byond Details:**
Any.

**First identifiable version:**
Pretty sure you could always spam the skill. At the very least, it is not from recent (2018+) versions.

**Comment by Khunkurisu** [comment]
When using the mate verb, only one window should be able to be opened at a time now.

**Comment by Kaseioo** [comment]
As of the Dragon Universe Classic 35.6.5 version, this issue still happens.
