### ISSUE TITLE
[Suggestion] Change the default tab from 'Stats' to 'Skills' for when the game detects the player not interacting with the game for some time

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#111]
**Is your feature request related to a problem? Please describe.**
More or less. Since staying in the Stats tab unfortunately creates some lag for the players, removing it from being the default tab for a AFK(-like) player would be nice. 

I'm using AFK since I can not think of a better term but I'm pretty sure it (sometimes) resets to that tab even if you're active in the game.
 
**Describe the solution you'd like**
Change the default tab for not interacting with the game from the Stats tab to the Skills (or maybe Other) tab since they are the one that lag the least.

**Describe alternatives you've considered**
Maybe change the 'default' tab to a 'not-selected state' where no tab would be selected and, with it, no info would be shown to the player. 

**Additional context**
N/A. All explained above, I guess.

**Comment by Khunkurisu** [comment]
Stat panels will now only reset after 10 minutes of inactivity.  Upon doing so, it'll move to the "Skills" tab, instead of "Stats".
