### ISSUE TITLE
[BUG] You can use the Soar skill while controlling moveable skills (such as Death Ball and Sokidan)

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#112]
**Describe the bug**
See title. It is possible to control a Ki Skill while on another Z-Level due to Soar, be it while the skill is charging or while it is in use.

**To Reproduce**
1. Use a controlable ki skill like Death Ball.
2. Use the Soar skill to change Z-Levels.
3. See that you are still able to control it. Or else, see that you are still locked in place due to the 'charging/waiting for launch' phase of the skill.

**Expected behavior**
The skills should either be immediately canceled or the player should be unable to use Soar while they are being used.

**Screenshots**
Gif from a player charging a Death Ball and then using the Soar ability:
![1j34LXzjH2](https://user-images.githubusercontent.com/81521485/113577672-0009c380-95f8-11eb-929d-8ab730881414.gif)
Gif from the same player using a Kienzan and then using Soar while still controlling the skill
![t9R2zArAum](https://user-images.githubusercontent.com/81521485/113577799-31828f00-95f8-11eb-9238-db020991ec67.gif)

**Byond Details:**
Any.

**First identifiable version:**
This bug was discovered in the 'Dragon Universe Classic r20210304' version.

**Comment by Khunkurisu** [comment]
This should be resolved in the next patch.
