### ISSUE TITLE
[BUG] It is possible to use the Soar ability while knocked-out if you still have energy

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#113]
**Describe the bug**
You can use Soar while knocked-out if your energy is not zero.

**To Reproduce**
1. Get knocked out.
2. Try to use Soar to change Z-Levels.

**Expected behavior**
The player should be unable to use Soar while knocked-out.

**Screenshots**
Gif from a knocked-out player using Soar:
![5VWxzojlEx](https://user-images.githubusercontent.com/81521485/113578633-7e1a9a00-95f9-11eb-92f2-e699114394cd.gif)
(No, the player didn't come out of KO after using the skill, the icon-state probably just got bugged)
**Byond Details:**
Any.

**First identifiable version:**
This bug was discovered in the 'Dragon Universe Classic r20210304' version.

**Comment by Khunkurisu** [comment]
This should be resolved in next patch.
