### ISSUE TITLE
[BUG] When activating an Amulet make the server freeze/lag

### ISSUE THREAD

**Issue by Mimikyufan** [DU-Devs/Dragon-Universe-Public#115]
**Describe the bug**
When someone uses dead zone portal the server will lag/freeze for a few hours.

**To Reproduce**
1. Active Amulet
2. Game will begin to lag/freeze

**Expected behavior**
Using Amulet should not make the server lag/freeze.

**Screenshots**
N/A.

**Byond Details:**
- Byond Ver 513.1542

**First identifiable version:**
Dragon Universe Classic Ver 35.5.8 PvP Server

**Comment by Khunkurisu** [comment]
This has since been resolved.
