### ISSUE TITLE
Beams Bug

### ISSUE THREAD

**Issue by Nishimiya-Shoko** [DU-Devs/Dragon-Universe-Public#117]
Describe the bug : 
Beams Skills are jerky and not continuous (All Beam skill Type)

1. Go to 'Skills'
2. Click on Beam or Turtle Beam Or Any Beams Skills
3. And when you fire a beam skill type the beams are jerky and not continuous

Expected behavior
The Beams are as if they were jerky instead of being continuous, this bug occurs in all directions including Diagonal and the overlays (the clothes start to blink)

Screenshots

![Beam Bug](https://user-images.githubusercontent.com/84858249/119688603-6963c100-be48-11eb-9fd5-c74d6de2943e.png)

![Beam Bug2](https://user-images.githubusercontent.com/84858249/119688669-797ba080-be48-11eb-92df-c25ec9b6e419.png)

![Beam Bug3](https://user-images.githubusercontent.com/84858249/119690954-72559200-be4a-11eb-8331-9964185a98f8.png)

Byond Details:
I have noticed this bug in Byond 513.1542

First identifiable version:
In Dragon Universe Classic 35.5.8 version

**Comment by Khunkurisu** [comment]
Does this happen every time you fire a beam?  I've seen this occur on occasion, but not consistently.

**Comment by Nishimiya-Shoko** [comment]
Yes every time i fire a beam it happens
