### ISSUE TITLE
[Suggestion] Reimplement several removed items and abilities.

### ISSUE THREAD

**Issue by randomoddguy** [DU-Devs/Dragon-Universe-Public#118]
**Is your feature request related to a problem? Please describe.**
Genocide was useful for RP purposes such as declaring aggro on an entire map, though the skill was worthless due to balance requirements by the existence of PVP. Spin blast I used frequently, as it had a wildly different firing pattern than any other attack in the game. Stun chips were very useful for rp purposes, but were too easy to remove. LSD, meanwhile, was a classic trolling item. It being removed along with the likes of brain scramblers, orbital cannons, and resource destroyers indicates a departure from the meme filled trolly nature of DU, which feels largely against the spirit of the game we all know and love (and hate). Of these though LSD was easily the least disruptive in the long term. I can understand the need to remove the others as in addition to trolling they were also OP, being able to permanently prevent other players from game progression. LSD however was also the easiest way to fuck with someone that didn't do permanent damage (in addition to being funny).
**Describe the solution you'd like**
Reimplement desired attacks, though possibly rebalanced. Reimplement stun chips and LSD, though possibly rebalanced. Additionally: Implement more items meant to screw with people that don't involve permanently wrecking their character. Non troll drugs are also honestly a good idea. Using consumables to get temp buffs is pretty standard in RPGs, and doing so at possibly a permanent cost (lifespan) has always been an interesting tradeoff.
**Describe alternatives you've considered**
I don't know some of these things were pretty much fine as they were. Similar alternatives that serve the same function could be fine as a replacement?
**Additional context**
Tens was bad at game balance lol.

**Comment by Khunkurisu** [comment]
While I understand it's controversial, the fact of the matter is yes, the game is moving away from its "trolly roots".  However, I completely disagree that the identity of the game is tied to that type of interaction.  Rather, I believe that what makes DU interesting and unique is the variety and freedom provided by the sandbox.  I won't say none of these things will make a return in one form or another, but I can not promise any of them will either.
