### ISSUE TITLE
tourney ring out bug

### ISSUE THREAD

**Issue by historysstrongest** [DU-Devs/Dragon-Universe-Public#120]
If someone suffers a ring out loss in the tournament, they could win instead of the opponent.

Steps to reproduce the behavior,
1. Enter Tournament
2. Walk out of the ring
3. Possibly win
4. Profit

If these very simple steps are followed, you might win!! That's the problem.

I don't know when this bug popped up, but I recall it being around for a while.

**Comment by Khunkurisu** [comment]
This should no longer be an issue, as DQs for going out of the ring no longer happen.  Rather, you simply get teleported back to the ring if you try to leave.
