### ISSUE TITLE
[BUG] Issues with Hotkey Setup

### ISSUE THREAD

**Issue by sgtwade** [DU-Devs/Dragon-Universe-Public#125]
Hotkey setup is super delayed/laggy

Whenever you drag up and down in the hotkey setup menu, only on the right side where you change the binds it has a massive delay before the scrolling takes effect.

Expected it to be smooth like the left frame.
https://gyazo.com/d7eb0e8068188d30ddae260b4e0c3211

Latest Byond Beta Build

Latest Version

**Comment by Khunkurisu** [comment]
This seems to be an issue that only started to appear after upgrading to beta, so I'm *thinking* it's a BYOND problem and not something I can fix.  That said, I'll leave this open until I can confirm that there's nothing I can do to improve the performance.
