### ISSUE TITLE
Form Manager[BUG]

### ISSUE THREAD

**Issue by FullNovaAlchemist** [DU-Devs/Dragon-Universe-Public#129]
**Describe the bug**
Form Manager has severe issues 
1. transforming into your highest form is the only way to descend (going into it and then pressing descend works)
2. descending otherwise is not possible
3. setting up 2 forms let's you cycle between them but with no way to descend anymore
4.removing or leaving out a form, from the chain doesn't work (Limit breaker would always be over ssj for example even if limit breaker was not clicked on)

**To Reproduce**
1. Go to 'to the form manager'
2. set up your form chain
3. transform
4. try to descend from any form other than your highest

**Expected behavior**
Descending from any form would either put you back to base or the form you set it to 

**Screenshots**

**Byond Details:**
5.0.513.1505 

**First identifiable version:**
First version containing the form manager after the wipe

**Comment by Khunkurisu** [comment]
already fixed
