### ISSUE TITLE
View Character (Sense Level 3) [BUG]

### ISSUE THREAD

**Issue by FullNovaAlchemist** [DU-Devs/Dragon-Universe-Public#130]
**Describe the bug**
After Mindswapping with another character the view character tab doesn't work correctly for both, it displays the same stats for both (for example kai race and stats despite one of them being a legendary saiyan) if 1 of them logs out the stat tab for yourself breaks entirely and only dipslays N/a

**To Reproduce**
1. Go to 'view character'
2. try to read the stats of both mind swapped characters

**Expected behavior**
the ability to read your own stats or the stats of the other person that has mindswapped with you

**Screenshots**
![view character 1](https://user-images.githubusercontent.com/45741577/125313842-ecc46d80-e335-11eb-94a3-df2e49e28ba4.png)
![view character 2](https://user-images.githubusercontent.com/45741577/125313877-f6e66c00-e335-11eb-9150-f58bc962a4b6.png)

**Byond Details:**
5.0.513.1505

**First identifiable version:**
 Update with the form manager fixes

**Comment by Khunkurisu** [comment]
I’m fairly sure this is already resolved
