### ISSUE TITLE
[Suggestion] Add "Fusion" to AP skill list

### ISSUE THREAD

**Issue by gahay35624525** [DU-Devs/Dragon-Universe-Public#133]
**My feature is not related to a problem.**

**A suggestion**
I wish for Aliens to obtain a new skill in their AP skill list choice called "Fusion" and possibly "puranto fusion" however it wouldn't actually be puranto fusion, it'd just mimic the way puranto fusion works with other aliens if they too possess the skill. It could possibly be called something else like "merge" instead and it probably wouldn't give as much as the puranto fusion gives. (I'm not sure how much it gives but I know it's based off of the average so I figure you can just manipulate it to make it scale to be like 50% of the average or something.) I figure this Ap skill would cost 50

**Alternatives**
Perhaps regular fusion shouldn't really be a choice but a possible learnable skill by a new rank called "metamoran" alien in which they obtain some bp similar to yadrat rank and the skill fusion. They would also spawn in checkpoint somewhere most likely the one next to the bank. 

If a mimic of puranto fusion wasn't available for some reason, then I suggest another sub type of alien, such as merge alien, which allows you to play as two small beings or average sized beings who can merge to become stronger temporarily or something as a play style(like gyren alien). Maybe if the coding is possible (I know this alternative is very, very out there.) you can even make it so they (as I would imagine it, it would just be a sprite of two characters walking together side by side) can split up and operate them from two different places, sort of like mind swapping between the two characters at any time. This could probably cost 50 since it's a drastic change like Gyren! 

**Additional context**
Aliens this is based off of, 
https://dragonball.fandom.com/wiki/Kado
https://dragonball.fandom.com/wiki/Abo
https://dragonball.fandom.com/wiki/Aka

**Comment by Khunkurisu** [comment]
I’m not adding anything to the Alien race nor do I plan to change that.  If anything I am more likely to remove the race entirely.
