### ISSUE TITLE
Fusion disabled due to bugs?

### ISSUE THREAD

**Issue by Barentz123** [DU-Devs/Dragon-Universe-Public#134]
Tried to fuse in the latest build (35.6.5) but it says it's disabled due to bugs? Both Potara and dance do this.  Not sure if this is intentional or not, I just found it strange since Fusion itself got some updates in the latest patch notes.

**Comment by Khunkurisu** [comment]
This is clearly intentional.  Why would it not be?  Do you think the game programmed its own text saying it was disabled?  Come on bud.
