### ISSUE TITLE
Majinize can be used infinately, allowing people to get infinate bp.

### ISSUE THREAD

**Issue by Chronx100** [DU-Devs/Dragon-Universe-Public#136]
**Describe the bug**
You can use majinize as many times you want on any of your alts by reconnecting the demon, then using majinize again.

**To Reproduce**
1. Create demon and get the demon rank that gives you majinize
2. Bring in your alt you want to boost
3. Use majinize on the alt
4. Reconnect the demon character and do it again, and again, and again

**Expected behavior**
Majinize is only designed to be used once, not infinately. This bug allows people to get game breaking amounts of bp. You can have a 39mil relative bp, but your static bp will be in the trillions or quadrillions, depending on how much you did the glitch.

**Byond Details:**
- any version id assume.

**First identifiable version:**

Whenever majinize was added to the game i assume. I just started this server and love it because it reminds me of old DU so i just want to see this fixed.

**Comment by Khunkurisu** [comment]
This should be resolved in the next patch
