### ISSUE TITLE
[BUG] Ships are broken.

### ISSUE THREAD

**Issue by PikachuOnAcid** [DU-Devs/Dragon-Universe-Public#138]
**Describe the bug**
When someone destroys your ship or if you destroy your own, when you make a new one, it has a chance to be someone else's ship interior.

**To Reproduce**
1. Go Click on ship in the science menu
2. Go inside said ship and see if it's the same interior
3. If it is then you're lucky, if it isn't then you got someone's ship.

**Expected behavior**
People get angry and annoyed or even fight you to claim "their" ship back without realizing the reason you're in their ship in the first place.
P.s the ship walls and floors reset upon rebooting of the server

**Comment by Khunkurisu** [comment]
can't reproduce this issue, and it has not occurred to my knowledge on the latest updates of the PVP server.
