### ISSUE TITLE
[Suggestion ]Neo Machine Mutant Tuffle 

### ISSUE THREAD

**Issue by DrakoDemonx** [DU-Devs/Dragon-Universe-Public#140]
Neo Machine Mutant Tuffle Revamp Jiren alien revamp is next
Achieved with body swap mod only tuffles can use this mod
Machine mutants should be able to use all modules except Overdrive and Rebuild with no negative bp gain effects as they are most machine 

Possession - This will be Minor hosts
When you take over a host you get 25% of there max bp the host wont lose bp from this like baby he got stronger with every host, the host will look the same, No special benefits 

Tuffleization: You should have the option to transform the host into a fully Tuffle hybrid, for short time This will combine 75% of your max bp and host bp, (No 100% for balancing Reasons) if the host is a saiyan they get exclusive super saiyan forms with extra bp, They will look the same in base form but with red lines on the face and red eyes, (Base icon changes) There super saiyan will have white hair, achievable if the saiyan already has it. https://dragonball.fandom.com/wiki/Tuffleization
Super saiyan 2 https://dragonball.fandom.com/wiki/Strongest_Form_1
Super Saiyan 3 https://dragonball.fandom.com/wiki/Strongest_Form_2
Babys Tuffle Golden Ape will be there final form but to get any of these forms you must make a saiyan a main host

**Comment by Khunkurisu** [comment]
This already existed previously and was removed.  It most likely will not make a return.
