### ISSUE TITLE
[Suggestion] Assassin Alien

### ISSUE THREAD

**Issue by DrakoDemonx** [DU-Devs/Dragon-Universe-Public#142]
Assassin Alien Available to elite alien (Max 1) (40 AP) 
2.5x BP Mod
Attacks have a chance to cause bleed damage
Has Time skip without needing to buy it with AP
Has a longer time skip than normal 
Opponent's in time skip take extra damage
Deadly Intent: User conceal his movements becoming unsensable and transparent for 15 seconds 
(Gyrens can still sense and see them)
Stat bonus granted by Assassin Alien 
+20% Speed
+50% Accuracy

Pure Progress
Allows its user to rapidly improve their fighting performance.
User Gains a bright Blue Aura
Multiplies current BP by 1.85x
https://dragonball.fandom.com/wiki/Pure_Progress

Assassin Alien Skills

Ki Clones
When moving around, User is able to leave duplicates of his ki, in order to make it hard to track him. https://dragonball.fandom.com/wiki/Ki_Clones

Time Prison 
User attaches a time cage to them, keeping them suspended in time for short while
(Gyrens Are Immune To This) https://dragonball.fandom.com/wiki/Time_Prison

Realized Power
User uses his Time Skip to dash straight through his opponent with a powerful punch. The opponent feels the effect of the punch after Time Skip wears off. https://dragonball.fandom.com/wiki/Realized_Power

**Comment by Khunkurisu** [comment]
While this is certainly more thought-out than most alien/race requests, I'm not looking to *add* new race option, nor more options for Aliens specifically.  I'll keep this on tab in case I decide to make a few races from alien archetypes when I inevitably get around to removing the race as a whole.
