### ISSUE TITLE
[BUG] Swords do not give bleed status effect

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#148]
**Describe the bug**
Sword do not give the bleed status effect. They are acting as if the player is unarmed. The BP and stats do not matter at all, if they were ever factored in the trigger formula.

**To Reproduce**
1. Get a sword and equip it.
2. Chop something.
3. Fail and notice that you hit that something with the blunt part of the sword or something like that.

**Expected behavior**
Swords should give bleed to whoever is hit (with all due calculations applied, of course).

**Screenshots**
N/A.

**Byond Details:**
514.1561 (server-side).

**First identifiable version:**
This bug was first discovered in the Dragon Universe Classic 35.6.5 version.

**Comment by Khunkurisu** [comment]
Swords are being reworked into a proper weapon system in the upcoming release, in which this has already been resolved (as well as a general rework of status effects like bleed anyways).
