### ISSUE TITLE
[BUG] Admins can not edit ranks in any way

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#150]
**Describe the bug**
Admins (level 4 and inferior) can not edit ranks. The option simply does not appear in the admin commands in any way (or was just renamed to something that I could not find).

**To Reproduce**
N/A.

**Expected behavior**
Admins should be able to edit ranks.

**Screenshots**
N/A.

**Byond Details:**
N/A.

**First identifiable version:**
Dragon Universe Classic 35.6.5

**Comment by Khunkurisu** [comment]
Technically not a bug.  You can add and remove the ranks, but the option to edit them does not currently exist.  The system is only bare-bones.  I may add such support in the future, but at this moment the features necessary exist.  Also I have double-checked, it, you should absolutely have the verb.  If that isn't the case, check again when the mythical upcoming update finally releases.
