### ISSUE TITLE
[Suggestion] Create a better way for admin-set gains to be balanced

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#152]
**Is your feature request related to a problem? Please describe.**
Yes, it is. Currently, admins can set a value for training forms (and overall) gains to be balanced, but it is actually really hard to balance it since the values are not so intuitive. It basically means admins need to test it the hard way. 

Also, sparring gains modifier seems to be behaving very weirdly. I was forced to put it in the decimals to try to make it in-line with the other gains settings since it was giving WAY more than the other training options (see attached screenshot). I'm putting this here since I do not know if this is intended or not.

**Describe the solution you'd like**
When changing the value for any gain-type, admins should be able to run a quick test of "How much would X BP-Mod gain by training this way with this value?", somewhat like the Other tab -> Show BP Gains feature, but instantaneous. It would make it a lot easier to set gains.

**Describe alternatives you've considered**
Manually testing each form of training with each race.

**Additional context**
Gains screenshot:
![image](https://user-images.githubusercontent.com/81521485/130529670-634259bf-868f-4e35-a81a-356f00ef02e3.png)
A human was gaining about 0.08~ BP every 5 seconds with those settings (though it varied by around 0.05 from some training forms), while spar gains were giving around 3.5~ BP every 5 seconds (active sparring, but inactive was also dangerously high).

**Comment by Khunkurisu** [comment]
In the next update, these have been removed.  On top of that, the entire training/gain system, and settings related have been remade from scratch.  Going forward, BP will be separated into unique 'tiers' and each tier's worth of BP will take roughly 2 hours of straight training to reach at base gain rate.
