### ISSUE TITLE
[BUG] Window-based build tab creates lag

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#153]
**Describe the bug**
The default hotkey M-menu build tab windows creates a lot of lag while it is open. 

**To Reproduce**
1. Open build tab.
2. See lag.

**Expected behavior**
The apparently static window should not lag the game so much, while the previous tab-set build tab lagged less. 
(I'm EXTREMELY sceptical of this, but a lot of players that I know says that it lags more than when it was a tab).

**Screenshots**
N/A.

**Byond Details:**
514.1561 (client-side). It should actually be any 513.x or 514.x version, since it is so old (newest versions are definitely less laggy in any place though).

**First identifiable version:**
N/A. Probably since it was first implemented.

**Comment by Kaseioo** [comment]
I've been forced to open this issue, sorry.

**Comment by Khunkurisu** [comment]
This is just not true.  There are some new lag issues with the latest byond releases when having a new window open (both hotkey menu and build menu do this), but they are nowhere to the point of causing the game to freeze for many seconds like the old tab used to do.  That said, the entire build system needs to be reworked (like most of this game), so it's still something to look out for improvements on at some point.

**Comment by Khunkurisu** [comment]
No longer an issue, since this doesn't even exist anymore for build menu
