### ISSUE TITLE
[BUG] Majinized players can attack their Majin-izer in all forms othan than auto attack

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#155]
**Describe the bug**
A player that Majinized another player can be attacked by any skill (blasts included) from that player. Only autoattack on the Majin-izer is disallowed. 

**To Reproduce**
1. Majinize someone
2. Get attacked by that player, by any means other than default melee autoattack, and die.

**Expected behavior**
I think this can't really be completely impeded but maybe just nulling any damage given by the majinized player should work (probably).

**Screenshots**
N/A.

**Byond Details:**
N/A.

**First identifiable version:**
Dragon Universe Classic 35.6.5.

**Comment by Khunkurisu** [comment]
should be resolved in latest test version
