### ISSUE TITLE
[BUG] Forced mate still in the game and not toggleable by admins

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#156]
**Describe the bug**
Forced mate still in the game and not toggleable by admins. 

**To Reproduce**
1. KO someone.
2. Force-mate with that person.

**Expected behavior**
This possibility should not be in the game anymore.

**Screenshots**
*N/A*.

**Byond Details:**
N/A.

**First identifiable version:**
Dragon Universe Classic 35.6.5.

**Comment by Khunkurisu** [comment]
Added an admin config option (in Social Mechanics) to toggle forcible mating.  I also cleaned up the language to be less... triggering and crass.
