### ISSUE TITLE
[BUG] It is possible to fly while Training and Meditating

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#159]
**Describe the bug**
It is possible to fly while Training and Meditating. The BP gains also add up normally (just like flying and hitting a peebag).

**To Reproduce**
First method:
1. Spam the hotkeys for Meditating/Training with fly at roughly the same time.
2. See that you enter fly and starts training/meditating after about a second.

Second method:
1. Meditate or train.
2. Scroll the mouse wheel up (possibly a few times, but it goes on the first try most of the times).
3. See that you fly and resume your previous action (in mid-air).
Edit: apparently this method does not work inside of ships and on the Otherworld (heaven, checkpoint and hell). Edit 2: also neither in Space or the Prison. (seems like skill issue to me since they can't use the first method and works just fine). 

This method seems to work only in places you could Soar before it was removed (it was removed and rather than being bugged, right? It doesn't work anymore).

**Expected behavior**
You should just either fly or train/meditate.

(This is definitely a bug, right? Right? The mouse scroll is really so simple that it appears like a feature, but since you can spam fly and train to do it, this strikes me more as a bug rather than something planned)

**Screenshots**
![image](https://user-images.githubusercontent.com/81521485/131150813-2ef75369-daf7-4c73-9523-df327e92bea7.png)

(spamming train and flight at the same time)
![video_XtieQTC8z2](https://user-images.githubusercontent.com/81521485/131150908-e47d8f8e-ac33-44f0-b7f2-a69153666b57.gif)

**Byond Details:**
514.1561 (server-side and client-side).

**First identifiable version:**
Dragon Universe Classic 35.6.5.

**Comment by Khunkurisu** [comment]
This should end up fixed in the next update.  That said, I find this hilarious and it looks really amusing.

**Comment by Khunkurisu** [comment]
I have decided to leave this in because it doesn't actually count as fly (as far as gains are concerned), and only works in locations where the ability to fly out of maps should exist (which is also currently broken :D)
