### ISSUE TITLE
[BUG] Reward-menu given BP Modifier is leechable by other players of the same race 

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#161]
**Describe the bug**
Reward menu given BP Modifier is leechable by other players of the same race. A human was given 0.2 extra BP modifier (making it go up to 1.4), and other humans could leech that BP modifier when fighting with that player.

When opening the Edit menu and disabling the bp_mod_leechable from 0 to 1, it would for some reason automatically turn on again after some time. I've also looked at the editConfig menu and didn't see anything related to this, so it should be a bug.

All players are seemingly starting with the var enabled, as well. The race does not matter for it to be turned on.

As in the title, players from other races can't leech the BP Mod from a player from another race, even if it is edited.

**To Reproduce**
1. Reward someone some BP Mod.
2. Fight with them (with a character from the same race).
3. Notice that your bp modifier increased to the same amount than other player.

**Expected behavior**
The BP Mod should not be leechable by default and the var should not turn on by itself. Or, alternatively, there should be and editConfig option for toggling it.

**Screenshots**
N/A.

**Byond Details:**
514.1561 (server-side and client-side).

**First identifiable version:**
Dragon Universe Classic 35.6.5.

**Comment by Khunkurisu** [comment]
While this is more of a work-around than anything, you can fix this by editing their bp_mod_leechable (I believe that's the name at least) var to 0.  Doing this before rewarding bp mod works best.  I may be able to add a popup after rewarding a bp mod asking if they should be leechable, and if they can leech others of the same race (so lowering the value works as well).

**Comment by Khunkurisu** [comment]
Removed bp mod option from reward- it can still be changed in the edit menu.  As BP mod effects gains and not just current bp, it would usually be better to edit bp_mult instead (it also can not be leeched).  Closing this now.
