### ISSUE TITLE
[Suggestion] Change admin commands Message and Narrate to have a large, Emote-like textbox

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#162]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I write more than 15 words in the message and narrate text boxes and then I can't see the rest of the words since they go to the text-void where no sight is allowed.

No, really. It's probably the thing that annoyed me the most with working admin commands. Please, I beg you for once, change it to use the same textbox as Emote (aka Me).

(It also doesn't let you copy paste multiple paragraphs sentences and it is surely the biggest evil done but I'm doing a Suggestion since it's technically is an enchancement rather than a broken function).

**Describe the solution you'd like**
Change the used text boxes of the commands to be a large, half-screen wide text box.

**Describe alternatives you've considered**
Writing the text in another place and then copy pasting every paragraph in a Message/Narrate.

**Additional context**
*Sentence being hidden on Message*.
![image](https://user-images.githubusercontent.com/81521485/131233945-ea5a5b8e-de4d-41d3-82c9-86d94a106fee.png)

*Same sentence on Narrate*.
![image](https://user-images.githubusercontent.com/81521485/131233965-782c71d3-0b22-453d-a651-8b052fa9b128.png)

*The exact same sentence but in the mightly Emote text box*.
![image](https://user-images.githubusercontent.com/81521485/131233991-19fc6c74-b5b9-4743-9537-3bc433008e8f.png)

**Comment by Khunkurisu** [comment]
done!
