### ISSUE TITLE
[BUG] Dice rolls do not show in OOC or IC chat tabs

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#168]
**Describe the bug**
Dice Rolls do not appear in the OOC or IC tabs. It only shows on the All tab.

**To Reproduce**
1. Use the Dice Roll command.
2. Change to the OOC tab or the IC tab.
3. Notice that the rolled value does not appear in it.

**Expected behavior**
Dice Rolls should appear preferably on the IC tab, sice it is most used for RP purposes.

**Screenshots**
N/A.

**Byond Details:**
N/A.

**First identifiable version:**
Dragon Universe Classic 35.6.5.

**Comment by Khunkurisu** [comment]
Dice rolls should now appear in "All" and "IC" tabs
