### ISSUE TITLE
[BUG] Big Bang Attack

### ISSUE THREAD

**Issue by Marrakae** [DU-Devs/Dragon-Universe-Public#169]
**Describe the bug**
Big Bang Attack lets you kill people in Safe zones

**To Reproduce**
1. Go to any safe zone with someone else in it
2. Click on Big Bang Attack
3. If you have lethal on and you have enough force, it will kill the person (or even just KO, it shouldn't do either)

**Expected behavior**
Just put people to 0% rather than KO or kill.

**Screenshots**

It'd just be a dead body in safezone

**Byond Details:**
- Version 513

**First identifiable version:**
513

**Comment by Khunkurisu** [comment]
This revealed an issue with all ki-based attacks ignoring safezones and other protections.  It should be fixed in the upcoming patch.
