### ISSUE TITLE
[Suggestion] Allow admins to toggle automatic bounties on players who use Planet Destroy

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#172]
**Is your feature request related to a problem? Please describe.**
Sometimes, in *RP* servers, people need to use Planet Destroy due to their character's actions. However, after they use it a bounty drone will follow the player around and try to jail them when they are knocked off.

**Describe the solution you'd like**
Having a toggle option for automatic bounties on players, since it exists more due to PVP servers and it's mildly (really) annoying.

**Describe alternatives you've considered**
Removing it from the base game. Why would players even need automatic bounties when they do it for any reason anyway?
(I just noticed I was using this field wrong for like 15 feature requests, sorry lmao)

**Additional context**
N/A.

**Comment by Khunkurisu** [comment]
Planet Destroy has been removed entirely from the game in the upcoming update.  It has only ever been used to troll, and better methods are available for use on RP (such as Disable Planet, and admin narration).
