### ISSUE TITLE
[BUG] Splitforms and Simulations drain HP and Energy when destroyed.

### ISSUE THREAD

**Issue by KovakinGaming** [DU-Devs/Dragon-Universe-Public#173]
**Description:**
This bug is that Splitforms that you create when destroyed by you act like they had been destroyed by another player and then drain the respective amount of HP and Energy, Simulations have this same property except they do not split your energy while active like Splitforms do.

**To Reproduce:**
Grab a simulation or make a splitform
Fight the sim/splitform until it gets destroyed
Look at HP and Energy.

**Expected behavior**
This should only happen when another player kills the splitforms, and should never happen when destroying the simulations.
**Screenshots**

**Byond Details:**
Version 513.1522

**First identifiable version:**
What is the earliest version of the game in which you found this bug to exist?
N/A (didn't test earlier than 513.1522)

**Comment by Khunkurisu** [comment]
this has been resolved in the current build!

**Comment by KovakinGaming** [comment]
This has not been resolved fully, Splitforms still drain.
