### ISSUE TITLE
Gyren Alien 

### ISSUE THREAD

**Issue by DrakoDemonx** [DU-Devs/Dragon-Universe-Public#175]
Will probably do a beerus god race as well to go along with the Assassin and Gyren ailen ideas i made
Don't remove aliens its stupid and pointless not everyone wants to be a boring saiyan there one of the most unique races 
this is based on what tens was trying to do with gyren alien he had a solid idea for them but was executed poorly

Gyren Alien Will Be Super Rare Choice For Aliens (Max 1 Per Wipe) (50 AP)
https://dragonball.fandom.com/wiki/Jiren%27s_race
![image](https://user-images.githubusercontent.com/88162655/135610143-2b9e7004-a624-45b1-a42d-63e6ad0624db.png)

3x battle power mod Jiren's race has extremely high battle power and potential see wiki
Gains x2 more bp
Can not use god ki
No Anger
Gyren Alien negates ui dodging effects
Immune to time skip
Can Not Be Stun
Takes No Knockback
Deals Increased Knockback When Attacking
40% Damage Reduction
No form but a percentage of power available
Gyren Power Up: Start out as 1% power can press g for next levels 30% 70% 100%
Upon reaching 100% Gyrens emit a red glow
Unleachable BP
Gyren Punches emit shockwaves 
Natural Barrier: Gyrens ki is powerful enough to serve as a barrier against considerably weaker attacks, can be powered up by going 100%
Meditation will be uninterruptible to anyone who isn't at or above their percentage
Stat bonus granted by Gyren alien
+40% Durability
+40% Resistance
+30% Strength
+30% Speed
+30% Force
+25% Accuracy
+25% Reflex
+60% Energy
+25% BP Cap

Jiren skills exclusive for them
![image](https://user-images.githubusercontent.com/88162655/135610469-972b1b15-b84b-4e75-a2dd-184fe642bc0b.png)

Gyren Meditation 5 minute cool down
Has a shield effect protecting the user
The user enters a deep meditative state for a short period of time, gradually gains stamina and energy .

Activated By: Holding the key for a short period of time until the meditation state is over, releasing too early will cancel and you will not get the recovery.

User flashes yellow as an indicator for the buff being activated.

Achieved By: Learning the skill with skill points.
![image](https://user-images.githubusercontent.com/88162655/135610696-12cc65a6-5e5c-4f3c-8055-fd3cb5f17326.png)

Power Impact 
The user pulls their hand back, charging a red energy blast, and then pushes their hand forward, firing the attack. The user can also guide the attack wherever they choose. Once the blast hits and "grabs" the target, it will travel as far as its user wills it to be and then finally release a massive explosion. 30 second cooldown

Upon hitting an opponent with Power Impact, the caster receives “Impact Bonus”, the caster flashes red for 15 seconds any ki or melee attacks used has a damage boost.
https://dragonball.fandom.com/wiki/Power_Impact
![image](https://user-images.githubusercontent.com/88162655/135611806-3096cc02-5179-4fe7-a26f-9a8f4dfc5c39.png)

Impact Bonus
Type: Passive
Activated when the user hits an opponent with Power Impact, the user begins to flash red constantly until the effect is over, giving the user a damage boost on both melee and ki attacks for a short period of time.
![image](https://user-images.githubusercontent.com/88162655/135612440-ad008adc-9481-4b0a-9997-c5d7ef84e970.png)

Counter Impact: Activates when hit, User flashes red for 3 seconds in that time the counter will be active After successfully countering an opponent's attack, User teleports to his opponent and surrounds them within a sphere of ki, electrifying them before it detonates, it will work like Hakai with trapping them in a big red sphere than explodes. https://dragonball.fandom.com/wiki/Counter_Impact
![image](https://user-images.githubusercontent.com/88162655/135612856-10dc5a2a-a4b2-4cbf-83ee-465b55116eb4.png)

Grand Charge: User Dashes in a straight line to the opponent with his shoulder while enveloped in a purple barrier deflecting attacks in the way and doing heavy melee damage.
https://dragonball.fandom.com/wiki/Grand_Charge
![image](https://user-images.githubusercontent.com/88162655/135613162-f45d3688-b83c-4370-bc73-c5ea37f64b48.png)

Fatal Impact (Grab) 1 minute cooldown
User grabs his opponent's hair, landing a heavy gut punch to the opponent before blasting them away with Power Impact.
Activating Impact Bonus
https://dragonball.fandom.com/wiki/Fatal_Impact

**Comment by Khunkurisu** [comment]
I'm going to be as polite about this as a possibly can (not that you deserve it, since you haven't been).  Aliens may or may not be removed, but that has nothing to do with wanting everyone to be Saiyan and that's a silly notion.  This game has far too many races with far too few unique features between them, and it makes it a nightmare to balance.  There's a damn good reason Xenoverse and similar games don't have 12+ races to pick from- and they have a much larger team.

As for the rest of this, I may add abilities, traits, and the like inspired by Jiren's moves and the moves of other characters in the series.  But as for the race itself?  It won't happen.
