### ISSUE TITLE
DemiGods

### ISSUE THREAD

**Issue by PikachuOnAcid** [DU-Devs/Dragon-Universe-Public#176]
I've got a couple ideas of pregod transformations that would help with people choosing to be demigods instead of the usual pick of being a Saiyan. Demigods should have 2 transformations, one with a multiplier of 1.5x that is just a bit lower than ssj and one that has 2.5x multiplier which would be lower than ssj3. Both transformations wouldn't have the usual cool aura effect or change of hair color, they would both have cool looking warrior armor. EX 
![image](https://user-images.githubusercontent.com/88221259/135773350-07587f15-1bb9-48ef-bd21-6692a08e21e0.png)
![image](https://user-images.githubusercontent.com/88221259/135773606-bc64c3db-1934-4afb-9960-698f096dc62e.png)

**Comment by Khunkurisu** [comment]
The armor can always be applied as a custom overlay for the form, since they have the option to be added.  Otherwise, Demigods now have a form that is similar in power to Pump Up, and can be acquired at around the same era.
