### ISSUE TITLE
[Suggestion] God Era Demigod Transformation

### ISSUE THREAD

**Issue by KovakinGaming** [DU-Devs/Dragon-Universe-Public#177]
**Is your feature request related to a problem? Please describe.**
This feature is not related to a problem, just that Demigods do not have a God Era transformation yet.

**Describe the solution you'd like**
I would like a God Era transformation with a name such as God's Realized Power, with a focus on Durability and Recovery, with minor increases in other stats, as well as the appropriate BP multi. Any suggestion for exact number is just a random idea and up for debate and change. Maybe a higher BP Multi than average God Forms, as Demi takes so long to train. 3x at 0% mastery, 0.3x at 100% mastery. You could unlock this at 90% Beyond God Mastery.

**Describe alternatives you've considered**
It could also be a transformation similar to Beyond God, very similar stats but draining stamina or Ki instead.

**Additional context**
 This could change hair to pure white as well as god ki aura changed to white, maybe with white wings and a back outline.

**Comment by Khunkurisu** [comment]
Demigods and Kai now have a form that they can attain *before* Beyond God, that is roughly on par with a similar Demon form, and focuses less on raw BP and more on lasting longer in fights.
