### ISSUE TITLE
[Suggestion] Frost Lord Fifth Form

### ISSUE THREAD

**Issue by RenLovesCake** [DU-Devs/Dragon-Universe-Public#178]
The suggestion of this is clearly to add the Fifth form to Frost Lords

I do think you need to have a way of getting the fifth form instead of getting it at the start by making the form have a bp requirement before you can actually access the form (Like Super Sayian), I also picture that the buff received by the Fifth form would be greater than Pumped Final Form.

Also, I imagine you would pick the icon for the form when you make your Frost Lord character
![image_2021-10-05_172931](https://user-images.githubusercontent.com/91992429/136105334-96f0f5cf-d9bf-48c3-aaad-06633efc3561.png)

**Comment by Khunkurisu** [comment]
I see no issue with this, but I'm looking to add transformations to races that lack them at the moment, rather than piling more onto a race with second most in the game.
