### ISSUE TITLE
[BUG] Character Deletion

### ISSUE THREAD

**Issue by josh11770** [DU-Devs/Dragon-Universe-Public#186]
**Describe the bug**
Deletes your save when you log out after being in the void
Prior to being in the void, I was meditating on Planet Kaioshin after having just used the dragon balls (earths or Kaioshins cant remember) before work i logged into being in the void.
**To Reproduce**
1.Login
2.if you see a black screen instead of where you logged out, log out then back in.
3.upon logging in you're still in the void, but will have basic stats and see 3 blue squares

**Expected behavior**
Be where you were when you logged out.

**Screenshots**
<details>
 <summary>Before and after screenshots</summary>
   <p>

![Stats DU](https://user-images.githubusercontent.com/20744155/138632738-26a1f27d-8f2a-49a0-a17c-5df6ef3eb3ec.png)

![stats after relogging](https://user-images.githubusercontent.com/20744155/138632742-6db1f6a1-4bb4-428c-8f0a-02f3af6aa2bc.png)
   <p>
</details>

**Byond Details:**
- Version (ex. 512, 513, etc): 
- 514.1569

**First identifiable version:**
What is the earliest version of the game in which you found this bug to exist?
Preview 20211010

**Comment by josh11770** [comment]
More Info here, after the server finished rebooting again, I was able to Log back into my character, Albeit Without any items besides Resources. so blueprints HBTC keys radars. those sort of things don't come back. All learned/wished skills are also gone.
<details>
 <summary>skills that remain</summary>
<p>

![remaining skills](https://user-images.githubusercontent.com/20744155/138648635-aaf77abd-3a34-4605-8595-e236ba109d82.png)

</p>
</details>

**Comment by Khunkurisu** [comment]
This does not seem to be an issue anymore, not sure which update fixed it.
