### ISSUE TITLE
[BUG] Forms Breaking

### ISSUE THREAD

**Issue by Spaceapples2** [DU-Devs/Dragon-Universe-Public#190]
**Describe the bug**
Going through forms too fast breaks them

**To Reproduce**
1. Have more than 1 forms active
2. Transform really fast through the forms

**Expected behavior**
One of the forms breaks and you're stuck with its overlay effects and cannot go back into them
OR the effects for all of the forms are broken 

**Screenshots**
![image](https://user-images.githubusercontent.com/93723914/140989892-1c84471d-cf27-4783-ac7f-8f6a892bed6d.png)
![image](https://user-images.githubusercontent.com/93723914/140989944-59198509-6558-4c45-b7ba-97e1d4f23f8b.png)
even trying to change the icon itself doesn't fix the issue for the aura

**Byond Details:**
- Version 513.1522

**First identifiable version:**
v35.7.6 - v35.7.8

**Comment by Khunkurisu** [comment]
I believe this is resolved in the latest release, but I'm not 100%.
