### ISSUE TITLE
[Suggestion] Bio-Android traits

### ISSUE THREAD

**Issue by historysstrongest** [DU-Devs/Dragon-Universe-Public#192]
Bio-Android currently suffers from a lack of traits so I'm going to list ideas for 4 traits here. Obviously the numbers I give are subject to change since I don't have complete knowledge of all the races' particulars.

**Saiyan Genetics**
Gives the player Zenkai (which means if you pick any other racial trait you just wouldn't have it), a Zenkai Mod of 0.75x, and also increases anger mod to 1.1x. Allows the player to invest in the What Doesn't Kill You trait.

**Icer Genetics**
Increases BP mod, and Adaptation. Decreases Recovery and Regen. (i don't really have any more ideas for this one)

**Namekian Genetics**
Increases Regen and Recovery, gives the player the stretchy arm grab, the Regeneration ability, and Death Regen. Also allows the player to invest in the Fervent Regeneration trait.

**Human Genetics**
Increases Adaptation, and increases Intelligence to 0.9x. Also gives Pump-Up(if possible), and allows the player to invest in the Unparalleled Ingenuity trait.

I was considering locking Super Perfect behind Saiyan Genetics, but it seems a bit unfair. It's up to you really, Khun.

**Comment by historysstrongest** [comment]
also, maybe going to your next form (like larva -> imperfect) would slightly increase some of your stats, like recovery. doesn't really have anything to do with traits though

**Comment by Khunkurisu** [comment]
implemented bio traits, generally inspired by this suggestion
