### ISSUE TITLE
[Suggestion] Icer trait

### ISSUE THREAD

**Issue by historysstrongest** [DU-Devs/Dragon-Universe-Public#194]
Heres some ideas for Icer traits. Numbers subject to change.
**Unrivaled Cruelty**
_You have a penchant for inflicting extreme pain and enacting cruel punishments. Upon injuring another person in any way, gain a static 5% bp boost for 20 seconds._

**You Will Die By My Hand**
_The lower your HP, the higher your powerup rate becomes, and the less energy it drains._

**Comment by Khunkurisu** [comment]
I like both of these a lot, and some variation of both will probably end up in the game.

**Comment by Khunkurisu** [comment]
Both of these have been added, albeit modified from how they're laid out here.
