### ISSUE TITLE
[Suggestion] More Demon traits

### ISSUE THREAD

**Issue by historysstrongest** [DU-Devs/Dragon-Universe-Public#195]
demon traits!!! numbers REALLY subject to change this time, i have no clue how balanced the first one is
also i really had no clue what to make a trait out of so i just went crazy, feel free to be honest about how much you dislike/like these
**Evil Incarnate**
_Your evil knows no bounds and cannot be contained. Your melee and determination damage are boosted by a flat 0.33 multiplied by the amount of Good alignment players on the server. (Locked into Evil alignment)_
**Sorcerer**
_Your time trapped in the depths of the Demon Realm have lent you an affinity for the magic arts. Imbue your energy attacks with fire, allowing them to do Damage Over Time(DOT), for 1.5 seconds a hit._

**Comment by historysstrongest** [comment]
Real Khun: i LOVE THESE TRAITS!!!!!!!!! IM ADDING THEM **RIGHT NOW!!!!!**
me: omg thanks khun

**Comment by Khunkurisu** [comment]
> Real Khun: i LOVE THESE TRAITS!!!!!!!!! IM ADDING THEM **RIGHT NOW!!!!!** me: omg thanks khun

deleting this suggestion thread for violating my freedoms
