### ISSUE TITLE
Bodyswap it's a bug.

### ISSUE THREAD

**Issue by Roundstage** [DU-Devs/Dragon-Universe-Public#30]
**Describe the bug**
If you bodyswap into someone, this people get all of their items deleted. Multiple peoples can bodyswap to the same body making a hilarious scene, this breaks the game so badly then you can relog and fight with your body and you will still with the power of the swap, you can also use this to bug your stats and even gets a negative stat.

**To Reproduce**
1. Buy a bodyswap module.
2. Bodyswap into someone.
3. Tell to someone bodyswap to your bodyswap.
4. Relog.
5. Repeat.
6. The game it's complete broken!

**Expected behavior**
Fix this item or complete remove it from the game, it's broken for a very long time and no one can even use it on PVP or RP.

**Screenshots**

**Byond Details:**
- Version (ex. 512, 513, etc):

**First identifiable version:**
What is the earliest version of the game in which you found this bug to exist?
32v DU, 2017
Stills up to the earliest version.

**Comment by Khunkurisu** [comment]
Body-Swap is disabled until a rewrite can be managed.
