### ISSUE TITLE
Dropkick change you screen color forever.

### ISSUE THREAD

**Issue by Roundstage** [DU-Devs/Dragon-Universe-Public#31]
**Describe the bug**
You use dropkick with other people, if you and this people have the same speed on will get the scream with inverted colors until relog.

**To Reproduce**
1. Get a Dropkick skill.
2. Dropkick into someone who has dropkicking you.
3. Have fun!

**Expected behavior**
It's not a gamebreaking bug, but it's a bug.

**Screenshots**

**Byond Details:**
- Version (ex. 512, 513, etc):

**First identifiable version:**
What is the earliest version of the game in which you found this bug to exist?
The Earliest Version.

**Comment by Khunkurisu** [comment]
Screen color should reset properly now after about half a second.
