### ISSUE TITLE
Beams invulnerability.

### ISSUE THREAD

**Issue by Roundstage** [DU-Devs/Dragon-Universe-Public#32]
**Describe the bug**
If you get in front of a roof and get beamed up to the roof direction that doesn't damages you, It also works with the blank tiles that represents the end of map.

**To Reproduce**
1. Go to a roof.
2. Get beamed up to the roof direction.
3. Ignore the beam beacuse that doesn't damages you.

**Expected behavior**
Fix that, it's very annoying on PVP.

**Screenshots**

**Byond Details:**
- Version (ex. 512, 513, etc):

**First identifiable version:**
Earliest Version.

**Comment by Kaseioo** [comment]
This bug referred to an issue where if a player was placed on the tile next to the void-border of any map and then beamed *against* that border, the player would take no damage at all.

I do not remember players beamed against any other type of structure not taking damage, however. (I may be wrong about it, though)

From what I could see, at the latest version (2021-03-04), this issue stopped happening. If I see it again, I will report it.

**Comment by Khunkurisu** [comment]
Closed if the issue seems to be fixed.  Can reopen if it occurs again.
