### ISSUE TITLE
A very dangerous thing.

### ISSUE THREAD

**Issue by Roundstage** [DU-Devs/Dragon-Universe-Public#33]
**Describe the bug**
With the update verb you can send all types of archives just by renaming it, it's not hard for someone who has lvl 4 upload a malicious archive and steal your informations or even put a RansomWare in your machine.

**To Reproduce**
1. Gets a archive.
2. Rename it to match a DU archive name.
3. See error.

**Expected behavior**
Fix that, it's a really dangerous thing and a security fail.

**Screenshots**

**Byond Details:**
- Version (ex. 512, 513, etc):

**First identifiable version:**
The Earliest Version.

**Comment by Khunkurisu** [comment]
Due to security concerns and an inability to address them (They're Byond's fault, not ours), we are moving Update() verb to level 5 only.  The verb has hardly worked properly since Byond 511 anyways, so it shouldn't be too big of a deal.
