### ISSUE TITLE
Hover chair simply doesn't work.

### ISSUE THREAD

**Issue by Roundstage** [DU-Devs/Dragon-Universe-Public#34]
**Describe the bug**
It's a item that doesn't work, it doesn't make anything.
**To Reproduce**
1. Buy a hoverchair.
2. Examine it.
3. See error.

**Expected behavior**
Fix that or remove it, it's a item without a function and costs some resources.

**Screenshots**

**Byond Details:**
- Version (ex. 512, 513, etc):

**First identifiable version:**
The Earliest Version.

**Comment by Khunkurisu** [comment]
Hover Chair item has been removed for the time being.  It may be re-added in a working state later on, but for now it is a waste of resources.
