### ISSUE TITLE
Pwipe also deletes admin buildings.

### ISSUE THREAD

**Issue by Roundstage** [DU-Devs/Dragon-Universe-Public#35]
**Describe the bug**
It's clear a PLAYER WIPE, and it's delete admin things too.

**To Reproduce**
1. Do a PWIPE verb.
2. See error.

**Expected behavior**
Delete just the player things and not the admin things. A option to only delete characters and items instead of all things should be great too.

**Screenshots**

**Byond Details:**
- Version (ex. 512, 513, etc):

**First identifiable version:**
The earliest version of the game.

**Comment by Khunkurisu** [comment]
Pwipe Settings verb now has a toggle for admin buildings being deleted on pwipe.  This verb also allows you to outright stop the map from being deleted at all- alongside items and feats.
