### ISSUE TITLE
[Suggestion] My personal suggestions.

### ISSUE THREAD

**Issue by Kyratio** [DU-Devs/Dragon-Universe-Public#37]
1. A more in-depth building system, the current one is imo better than the old one, but still very ech compared to RPT's. They have interesting mechanics like speed adding 10% of itself to your off/def and speed actually being a viable build with combo warping and such, or the fact it feels like you can have builds to *actually* counter other builds and there aren't just either in the *new* DU dura builds everywhere, or in the OG DU, everyone running around with as much anger/regen/recov as possible with speed being an almost useless stat.

2. Better RP options for the hosts, such as being able to manually set things like SP costs for skills, resource cost for science, and so on. Easily set where races spawn without the spawners respawning or you being forced to make all spawn in one place, etc. Nice things like that.

3. Honestly, more interesting skills. Things that actually work off of specific builds kind of like that fucking North Star meme, but not memey.

4. The ability to edit Icer form multis without them reverting back when the person relogs.

5. Maybe the ability to make custom techniques? Such as an admin can set a multiplier to BP or any other stats to a skill, or damage multi and all that as a beam and so on, name it, set how many SPs it takes or if it should only go on a specific person, and so on. I imagine this would be harder to code than new skills, but if you could do this, it would completely null that point and be amazing.

I could keep going but honestly, if just 3 of these 5 happened I'd be happy already.

**Comment by Khunkurisu** [comment]
Closed by request of the OP.
