### ISSUE TITLE
Suggestion for Shikon jewel item 

### ISSUE THREAD

**Issue by ty162** [DU-Devs/Dragon-Universe-Public#43]
Make  Shikon jewel a actual item that spawns on earth only for none demon races they can use the shikon jewel to power boost them selfs but if used to long the jewel starts eating their health, for demon race if used it will give them the ability to transform any more shikon jewels used by them after that will add a permanent bp boost to their base maby like 2% or somthing nothing to crazy

**Comment by Khunkurisu** [comment]
Shikon Jewels might seem neat in concept, but they're far too easily abused in their current state.  Making them freely available would completely devastate the game's balance.  A similar concept with better balance may be considered in the future, but it is unlikely.
