### ISSUE TITLE
Lsd acting strangely.

### ISSUE THREAD

**Issue by Roundstage** [DU-Devs/Dragon-Universe-Public#51]
**Describe the bug**
Lsd just start working after you relog, sometimes while under effect of it without reloging you can't drop some items or use some skills like in Soul Contract or league things.

**To Reproduce**
1. Buy a LSD
2. Use it
3. See error

**Expected behavior**

**Screenshots**
It's a pretty useless item, just delete it from the game.

**Byond Details:**
- 513

**First identifiable version:**
Last tens version.

**Comment by Khunkurisu** [comment]
LSD has been removed from the science menu.  Still available via admin verbs.
