### ISSUE TITLE
A bunch of techs

### ISSUE THREAD

**Issue by Roundstage** [DU-Devs/Dragon-Universe-Public#53]
**Describe the bug**
Firewall: Useless if bodyswap it's removed.
Drone-AI: Extremely unbalanced, Bugged and every server bans.
Scrap-Absorb: It's too shorty, it's very rare use this on combat, maybe a rework will be great.
Spawn Redirector: Everyone bans it, just work to trap peoples and ruins the game.
Pod Race Computer: Complete Useless, but it's a funny mechanic, maybe make a tournament system for it will be great.
Gun (And Ammo): Extremely unbalanced, can break a game easily by making some full reflex build invincible.
Emp Mine: Extremely unbalanced, literally ruins the game for anyone who plays with androids and cybers but it's cheap to buy.
Brain Scrambler (And Blocker): It's a pretty cool mechanic but every server bans it and isn't fair for new players, they can be literally stucked forever on a planet depending of server configs.
Diarrea Injection: Complete Useless.
Hand-Drill/Shovel: Complete Useless.
Car: Complete Useless.
Blast-Absorb: Bugs sometimes, absorbs skills but not delete they blast icon and cache.

**To Reproduce**
1. Buy this techs
2. See error

**Expected behavior**
Rework or delete everything here but Blast-Absorb(this have a minor problem).

**Screenshots**

**Byond Details:**
- 513

**First identifiable version:**
The last tens update.

**Comment by Khunkurisu** [comment]
Make an individual bug report or feature request for changes to specific modules.  Several items in this list are removed from science tab, but not all.
