### ISSUE TITLE
Precognition it's disappearing

### ISSUE THREAD

**Issue by Roundstage** [DU-Devs/Dragon-Universe-Public#54]
**Describe the bug**
When precognition's ends instead of entering in a charging countdown, it disappears and never comes back, making your waste 25 AP. What causes the bug it's the Precog var that goins to 0 when Precogs var hits 0.

**To Reproduce**
1. Get precognition.
2. Use it until precogs hits 0.
3. Lose your precognition.

**Expected behavior**

**Screenshots**
https://cdn.discordapp.com/attachments/348839765782691840/726946437220270131/unknown.png

**Byond Details:**
- 513

**First identifiable version:**
Last Tens version

**Comment by Khunkurisu** [comment]
This was incredibly depressing to fix.  As I suspected, there was a simple typo in one of the cases where precogs was decreased.  Instead of decreasing 'precogs', 'precog' was being decreased.  This disabled the skill entirely after one use, instead of decreasing the number of charges.
