### ISSUE TITLE
Sticky Cloning Tank

### ISSUE THREAD

**Issue by Roundstage** [DU-Devs/Dragon-Universe-Public#55]
**Describe the bug**
It's simple, you buy it and if you get it on your inventory you will never gonna drop it! That will be with you forever!

**Screenshots**
https://cdn.discordapp.com/attachments/348839765782691840/726948295577960530/unknown.png

**Byond Details:**
- 513

**First identifiable version:**
Every single version that i tested.

**Comment by Khunkurisu** [comment]
It is now impossible to get a cloning tank in your inventory through normal means.
