### ISSUE TITLE
[BUG] bodswap resets hotkey

### ISSUE THREAD

**Issue by ty162** [DU-Devs/Dragon-Universe-Public#57]
**Describe the bug**
 body swap resets hotkey so I have to manually add my hotkeys back
**To Reproduce**

**Expected behavior**
not to lose my hotkeys
**Screenshots**

**Byond Details:**
- Version (ex. 512, 513, etc):

**First identifiable version:**
What is the earliest version of the game in which you found this bug to exist?
i believe the last to I used body swap that's when exgen had added ssjg for sayains

**Comment by Khunkurisu** [comment]
This issue will likely go unresolved until the hotkey system is reworked in its entirety.

**Comment by Khunkurisu** [comment]
Despite my previous statement, this issue has actually been resolved in the current beta release.  Hotkeys are not *perfectly* maintained, but they are no longer reset, either.  Instead, you only lose the hotkeys for skills the new body does not have.  This is likely the best we can do without a total overhaul of the hotkey system.
