### ISSUE TITLE
[Suggestion] bodyswap rework

### ISSUE THREAD

**Issue by ty162** [DU-Devs/Dragon-Universe-Public#58]
**Is your feature request related to a problem? Please describe.**
body swap timer is to small, no gain or purpose for actually body swap other than avoiding death to you and being able to use the person skill.
**Describe the solution you'd like**
through a bug I discovered that I could clone a body swap version of a alt , so my alt was free from the body swap put I still had a baby version of his body. it be cool if you body swap someone you can copy their DNA and use their body whenever so the players don't get annoyed not being able to do anything.

**Describe alternatives you've considered**
you can also allow body swap users to leech bp off players so they're more of a purpose to hunting down players with body swap but to balance this you lose all the bp you gained if you die. I think this will be easy to implement since android can technically gain normal bp in this game only for a brief movement when they absorb someone after they start training It usually goes away.
**Additional context**

**Comment by Khunkurisu** [comment]
Body Swap does not exist in the current versions any longer.  If it is re-added, it likely will not function in any way similarly to how it does now.
