### ISSUE TITLE
[Suggestion] Stamina/Transformation Rework

### ISSUE THREAD

**Issue by MazigoGH** [DU-Devs/Dragon-Universe-Public#59]
**Problem**
Alright, where to begin...
Don't you lot think there are a little too many transformations by now? Of course, expecting a dozen more was inevitable, not like they really make a difference in gameplay (just palette swaps, really). But onto the issue: 

What is the Stamina bar if not one of, or even _the_ most **useless** stat in the game? I think everyone knows that. Since the past year and a quarter that I've previously played, it only served to gauge how many times you can use the Zanzoken skill in rapid succession-- A move that only serves as a surefire way of bumping into your opponent with auto attack on without holding your arrow keys, or to ensure an easy win via beam-locking. Nothing more. It could also determine how many times you can dodge a melee attack in the past, but that has long since been scrapped... _I_ _think._

But no, my main gripe with what's included in whatever... this game currently is, are **Transformations**.
Transformations, for the long term, are also one of the more broken, yet simultaneously useless mechanics in-game; It does nothing for your stats (and before acting smart, ascension is what increases your stats, not necessarily attaining a new form) in any meaningful way other than the dramatic boost it provides after initially tapping into it.
The best example for this would have to, of course, be the Omega Yasai forms. Sure, getting Omega Yasai 1, 2 and 3 before anyone else is great and all, but this results in the majority of other races becoming useless (unless you were a cybernetics whore or the Legendary Omega Yasai), though this aspect diminishes with each new form, which I'm a bit thankful for. Still doesn't fix the problem; You should feel accomplished, getting this form and all. But all I feel is incapacitating boredom.... 
after 24 hours. 
Yes. In 24 hours, this form you wasted hours of your life trying to achieve? It becomes **NOTHING** once someone else ascends. And that's when I feel disappointment.

I'm not sure if this was fixed since the last time I played, but global leech is the main reason this keeps happening on an endless loop. Why should I feel weary to pop my trump card solely because someone else can just passively absorb it and reach my level in 5 hours? What's worse, I'm only delaying the inevitable and slowly losing the golden opportunity to use it meaningfully. It's like watching Draggin Ball Super-Duper all over again. **Congrats, your base form is now obsolete!** Your 'trump card' is now your base with potential 'drawbacks'!

It's become so bad in recent updates, I'd opt to remain in base form as a Yasai, just because the boost to Omega Yasai Blue was so miniscule that it was not worth the increased energy drain. Strangely enough, I found myself liking that twist. This twist, alongside the recent beta release featuring the debut of Omega Yasai Royal Blue, has reignited an idea I've discarded for over a year now:

**Solution**
Now with that out of the way, let's get to the very reason I decided to type this out.
Diversity between forms have finally increased since Omega Yasai 4 now that the Blue forms consume **Stamina** rather than
Energy. That's cool and all, but that only means Blue is a viable option for me now... to dump all the energy I got into beams and stun blasts. The only real thing I'd be losing is the option to flashstep across the map until **I stop moving for a sec,** right? And that isn't any fun, but the concept has promise.

So using this as inspiration, I propose a way to breathe meaning into this stat is by using Stamina as not just a separate consumable, but the deciding factor in how potent/beneficial the Blue forms become. By this I mainly mean how much power it grants the user; Just like the concept of Battle Power dropping when your Health/Ki is too low, so too would be the case if your Stamina is too low before entering the form.

OTHER than transformations however, Stamina could also be used to decide a majority of the player's actions and how effectively they can be done. Instead of just regeneration, it could determine the duration it takes before you regain consciousness, how effective melee attacks can be depending on how much you have in reserve, and even movement alongside the speed stat. All of these aspects will be touched on in future suggestions as there are much more that I don't have the time to list here.

**Alternatives**
Of course with this in mind, it does not have to apply to just Blue, but other forms for all races, too! Not just Yasais. Transformations can take a certain percentage of stamina to access, for example. If anything, this mechanic would fit the ascended Yasai and Golden Frost Lord forms perfectly if applied a little differently; Instead of deciding the static BP boost proportional to your current Stamina, the form can gradually diminish in power once your Stamina is critically low. In some cases it would deny you the option to access your full power entirely, and can also decide the duration it takes to transform once you're below a certain threshold (SS3 Goku vs Kid Buu & SSG/SSB Goku vs Broly as references). Said threshold can differ with each transformation. If you'd like, certain forms/techniques can affect Stamina consumption as well, such as the Kaioken.

**Additional context**
![image](https://user-images.githubusercontent.com/67564771/85972605-73faa980-b99e-11ea-8219-8bee6b5c9362.png)

This would force players to play smart with their usage of Blue in battle, as well as figure out when and how they can harness it to its fullest potential. Sure, you can turn it off and on like a light switch all you want like all your other forms... but with this in mind, would that be the practical thing to do? This'd not only make the transformation below Blue have far more meaning than just stat benefits, but opens the window for future ideas like God-to-Blue form switching to actually be a viable strat, and in turn generate exciting, strategic gameplay!
`<font size="5">To be honest, a BP boost to Blue wouldn't hurt in this case. It needs a little more love.</font>`

**Comment by Khunkurisu** [comment]
This has been done to a lesser degree since the original posting.  However, I'm leaving it open as a reminder to myself to actually go through and rework the other transformations besides just the God Ki ones.
