### ISSUE TITLE
Shockwave in a Genkidama like skill stops your character forever.

### ISSUE THREAD

**Issue by Roundstage** [DU-Devs/Dragon-Universe-Public#63]
**To Reproduce**
1. Shockwave a supernova, genkidama or death ball while it is charging.
2. Stuck the person who was charging it forever.

**Expected behavior**
Fix that.

**Screenshots**

**Byond Details:**
- 513

**Comment by Khunkurisu** [comment]
Movement should no longer be disabled if you're knocked back by shockwave while controlling a genki dama skill.
