### ISSUE TITLE
[Suggestion] sayain ape form

### ISSUE THREAD

**Issue by ty162** [DU-Devs/Dragon-Universe-Public#64]
**Is your feature request related to a problem? Please describe.**
ape form currently has a short timer and it hard to activate moon

**Describe the solution you'd like**
let the moon be used in inventory  and remove timer only way to turn ape form off is by cutting the tail with a sword or kienzan. and allow moon to be used in invitory and add a way for ape user to revert manually but keep the bp loss for going ape form 

**Describe alternatives you've considered**
make golden ape a stronger version of ape form possibaly 
**Additional context**

**Comment by Khunkurisu** [comment]
Moons have been disabled/removed, replaced by Power Orb skill.  See v35.5.15 for details
