### ISSUE TITLE
[Suggestion] asorbe skill for demon/ maby other races

### ISSUE THREAD

**Issue by ty162** [DU-Devs/Dragon-Universe-Public#65]
**Is your feature request related to a problem? Please describe.**
absorb skill only used for killing and bp increase

**Describe the solution you'd like**
let the absorbed skill give skills like death regen if you absorbed someone with death regen very small stat boost like .1x but all of it is lost if the player is killed.

this doesn't have to be demon exclusive tho just giving a possible idea for absorbed skill for other races as well

**Comment by Khunkurisu** [comment]
Good suggestion.  Next major update will be overhauling how Majin work.  During that update, Absorb will be getting a major revamp.
