### ISSUE TITLE
[Suggestion] Bio Engineering

### ISSUE THREAD

**Issue by joejoe3421** [DU-Devs/Dragon-Universe-Public#66]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
New Type of Computer- Bio engineering Computer
Would allow for genetic creations for things such as bio warriors, custom bio androids etc.
The computer would alow us players to make a custom bio warrior/race type of thing by using dna containers on the machine. I'll explain more below.

The computer has 3 base Options after the Use command is used on it if it currently has no active project.
*Build Android Template(Requires a blank non altered Android body near the machine to begin)
*Grow Genetic Template(Requires a FILLED DNA container to begin.)
*Cancel
The project will need to have 99%-100% completion of dna integration to be fully formed and genetically stable. I'm thinking unstable could mean something like possible shorter life span or something goes wrong where it gets a stat randomized at birth which could be good or bad(most likely will be bad) like a mutation. Since it is technically a type of clone the lifespan is short as usual upon birth.
Building or growing a template starts the project setting the computer to the active project state. 
*Building an android base simply makes the structure metalic meaning brain and bone structure are metal so no anger, but can be healed by robotics tools and regenerators while allowing use of organic based techniques and slightly higher bp when using cyber bp but all the drawbacks of it and modules. Also allows the implantation of 1 module into the template without it's side effects.(like manual absorb or something cyborgs can get)
*Growing a genetic base means it's grown similar to how cell was made and takes after the dna put into it.

Once the computer is in active project mode when using it different options appear.
*Add DNA(Upon adding DNa from a dna container the container is emptied out.)
*Grow Missing DNA.(uses the current DNA the project already has to grow the remaining DNA to reach 100%. So if someone uses the DNA of a Saiyan, Frost Demon(icer), and Namekian the initial start point for each amount of DNA would be 10% and in the end up as around 33.33% of  saiyan, frost demon and namekian DNA.). Maybe this could take a month of in game time or a set time that admins can set for rp servers
*Create Life Form(Births the lifeform as they currently are no matter what state they are in. Allows the User to name the race in which have have created assuming the race isn't 100% of a single race already. Takes the computer out of active project mode.)
*Info(gives the user a read out of the life forms current stat mods and abilities it has inherited from the DNA it was from from.)
*Destroy project.(sets the computer to self destruct causing a very small explosion like an android death erasing both the computer and the project inside.)
*DNA authorization lock(So people can't mess with your project.)
*Cancel(always good to have a cancel button. basically is the back button)

DNA based abilities(based on percentage)
*Any DNA experiment that is 100% of a race is basically a clone of that race with it's stat mods and clone lifespan.
Saiyan
	*20+% Slight Zenkai mod
	*30+% Ability to have + 1 transformations
	*50+% possible tail(possible oozaru, never gains control)
	*75+% higher chance to have a tail and better zenkai mod
Frost Demon(Icer)
	*20+% Slight increase to gravity mastery base mod
	*30+% Ability to have +1 transformations
	*50+% Higher gravity mastery base mod and transformation multiplier slightly higher
	*75+% Ability to have +1 transformations
Namekian
	*20+% Slightly higher health regen mod
	*30+% Possibility to get the regen skill
	*50+% Slightly higher meditate mod and better blast homing
	*75+% Gains better meditation mode along with ability to use puranto fusion with anyone who shares any of it's DNA.

Alien
	*20+% Chance to gain a Random skill at birth
	*30+% Chanse to be able to breath in space
	*Not sure what else aliens can even do that would make sense here
Kai
	*20+% Higher meditate mod
	*30+% Higher ki blast tracking
	*50+% Slightly affected by the buff kai get in heaven and kaioshin
	*75+% Completely affected byt he buff kai get in heaven and kaioshin
Demon
	*20+% grants the ability to imitate others
	*30+% Affected by the never dying of old age while in hell thing
	*50+% Slightly affected by the demon buff gotten in hell
	*75+% Grants the ability to use soul contract
Demi-God
	*20+%  Lower life span
	*30+% Higher BP mod
	*Not Sure what else they even get
Earthling
	*20+% N/A
	*30+% Higher Meditation Mod
	*50+% N/A
	*75+% Can learn third eye
Tuffle
	*20+% N/A
	*30+% N/A
	*50+% Slightly Higher intelligence mod
	*75+% N/A
Majin(Due to majin DNA nto being able to be used in DNA containign i wasn't going to put this but in case that changes i will anyway.) Maybe android 21 will make it after all.
	*20+% Higher regen mod
	*30+% Higher skill mastery Mod
	*50+% Ability To absorb people like a majin
	*75+% Death regen slightly weaker than a majin
For simplicity sake maybe only pure breed dna can be used in the machine.
Demon and Kai DNA in the same being should probably cause DNA unstability and corrosion meaning the stronger they get the lower their lifespan becomes as the universe trys to correct the issue

For stat mods simply add up all the mods of a certain type in the DNA so if there is 10 different DNA parts then divide them by 10 to get the average of them all. So strength would be all the strength mods added up then divided by how many different DNA are involved and so on.

This could also be the beggining of more hybrids when breeding like half saiyans are now but more in dept

**Comment by Khunkurisu** [comment]
Far too complex and doesn't really fit in with the style of gameplay I'm working towards- at least for now.
