### ISSUE TITLE
[Suggestion] fusion

### ISSUE THREAD

**Issue by ty162** [DU-Devs/Dragon-Universe-Public#68]
give kais the option to defuse by using the dragon balls to remove their permanent porta fusion

they did it in the show so it be fair if we can do it here too

**Comment by Khunkurisu** [comment]
"They did it in the show" is an awful reason to add something to the game.  There's no reason to allow Kai to defuse.  It gives them a BP boost and better stats, then after a while the fusion restrictions are lifted.  This is a silly idea to add, and nobody should have a reason to use it.

**Comment by ty162** [comment]
> "They did it in the show" is an awful reason to add something to the game. There's no reason to allow Kai to defuse. It gives them a BP boost and better stats, then after a while the fusion restrictions are lifted. This is a silly idea to add, and nobody should have a reason to use it.

alright I know that wasn't a good reason I was just lazy to write in the details thought you would just consider it as a possibility with all thing your adding. 

for a actual reason the reason why they need defuse is because they can't use genetic so they can't lower stats if they want to change builds. or permanently unable to join tourny kinda sounds harsh. I mean don't have to give them defuse option but a way to go to tourny would be nice so they can join tourny again. also another reason is their that 1% of people that fuck up and click the wrong option accidently fuse not sure how tf they manage to accidently fuse but good to be able to fix that.
you can make the defuse a little bit harsh for balancing reason like if they defuse they start with the bp the originally had at the start of  the fusion or their base bp after defusing is set to 1 so they kinda got to start all over kinda like focus shin reset
