### ISSUE TITLE
[BUG] egg bug

### ISSUE THREAD

**Issue by ty162** [DU-Devs/Dragon-Universe-Public#69]
**Describe the bug**
their a weird bug that spawns you in the void but you treats you as someone egg
I can't tell if it's player place eggs in the void or some weird glitch

**To Reproduce**

**Expected behavior**

**Screenshots**

**Byond Details:**
- Version (ex. 512, 513, etc):

**First identifiable version:**
What is the earliest version of the game in which you found this bug to exist?

**Comment by Khunkurisu** [comment]
Need more info, would appreciate if someone could give some.

**Comment by Kaseioo** [comment]
This issue report relates to one that I have knowledge of. 

Basically, when you create a character from a race that has eggs avaliable for you to be born of, you **sometimes** will spawn in a void-like area (an all-black space, don't really know if it is a void or simply a render error), where hotkeys do not work and you can only use verbs by typing then in the chat box.

The eggs are **not** placed in the 'void; it is the player born from it that appears in a 'void'. From what I noticed, the player also does not inherit neither Battle Power nor Energy from the person who placed that egg.

Relogging seems to fix the 'void' issue but you do not get your BP or Energy.

**Comment by Khunkurisu** [comment]
This should be resolved in the latest patch.  Being born when your planet has been destroyed or from an egg with an invalid location should now simply send you to spawn or failing that, to jail.
