### ISSUE TITLE
[BUG]Fusion is Affected by Incline

### ISSUE THREAD

**Issue by RyukiSen** [DU-Devs/Dragon-Universe-Public#73]
**Describe the bug**
Incline makes Fusion/Potara Useless, because it automatically makes the Fusion's Age 0.

**To Reproduce**
1. Fuse with a Player (Potara Or Fusion)
2.Have a Demon with their Soul check Soul Info
3. See error

**Expected behavior**
We've expected the age to remain/average out so that the Incline wouldn't completely affect the Fusion/Potara's power.

**Byond Details:**
- Version 512

What is the earliest version of the game in which you found this bug to exist?
Latest Release.

**Comment by Khunkurisu** [comment]
Fusion mobs now get the average age of the two fused beings.
