### ISSUE TITLE
[Suggestion] Observe/Advanced Observe adjust

### ISSUE THREAD

**Issue by joejoe3421** [DU-Devs/Dragon-Universe-Public#74]
**Is your feature request related to a problem? Please describe.**
Not particularly. It's just a little powerful for getting information.

**Describe the solution you'd like**
Observe has only been seen used by kai and should really only be learnable by kai unless they teach someone else while advanced observe should probably be ranked kai only type thing

**Describe alternatives you've considered**
Increasing the cost of observe to none divine races to to extremely high number and advanced observe to an even higher number

**Additional context**
They are very nice skills

**Comment by Khunkurisu** [comment]
Observe is classified as a utility ability, not a divine ability.  I have increased the cost of Advanced Observe significantly.  I'll consider racial limitations to it in the future.  For now, this will have to do however.
