### ISSUE TITLE
Skill tornament  Power up bug

### ISSUE THREAD

**Issue by lucateck** [DU-Devs/Dragon-Universe-Public#75]
**Describe the bug**
during a skill tornament, i noticed  that my power up was trash , despite having like 3x rec, making Powerup build totally worthless, and getting my ass kicked.But this happened only in the skill tornament. outside of it, it worked just fine.
**To Reproduce**
enter a skill tornament, and try to power up, if you have more than 1x, you should notice how slower it got.

**Comment by Khunkurisu** [comment]
Skill tournaments purposefully lower BP gain from PU, beams, etc.  They are meant to be about builds and skill choice, not BP.

Not a bug.
