### ISSUE TITLE
[BUG] Teaching Custom Buff gives other Limit Breaker

### ISSUE THREAD

**Issue by RedStorm99** [DU-Devs/Dragon-Universe-Public#76]
**Describe the bug**
Any time I teach someone a custom buff I have made it turns into limit breaker. And multiple copies of limit breaker at that. They have to forget it multiple times
**To Reproduce**
1. Learn a custom buff and edit it with transformation
2. Attempt to teach someone the buff
3. It doesnt work every time but if you know limit breaker it seems to teach them that instead

**Expected behavior**
I expected it to teach the custom buff i made not limit breaker
**Screenshots**
I dont have any screenshots at the moment when it happens again i can get screenshots
**Byond Details:**
- Version (ex. 512, 513, etc):
v513.1528
**First identifiable version:**
What is the earliest version of the game in which you found this bug to exist?
v35.5.5

**Comment by Khunkurisu** [comment]
Does this only happen if it has the transformation attribute?  I need more info to find out what's causing this.
