### ISSUE TITLE
[BUG] Fusion Dance/ Potarra to Break BP Levels

### ISSUE THREAD

**Issue by Artichs** [DU-Devs/Dragon-Universe-Public#77]
**Describe the bug**

An insane BP bug that can be done using fusion dance/ potara earrings and soul contract. Pre-ascension it is a bit more controlled since BPMs are consistent and require too much of a grind to reproduce with OP results, but nonetheless still doable. The effect of the bug is amplified greatly when the fusion partners are ascended in BPM, being able to take your un-fused character from millions to billions within about three uses or less.

**To Reproduce**
1. Soul contract the person that's going to be dominant in the fusion. Then have two other people (not the soul contract holder) fuse.
2. After the two people fuse, they'll obviously become a new entity. The server decides whatever relative base BP the fusion entity gets brought to, but it's nothing out of the ordinary in range. The problem comes in with soul contract.
3. Using the soul contract holder, adjust the BP of the dominant fusee to it's max. Do this even if there will be no BP increase at all.
4. Upon defusing, adjust the BP of the same person again. You'll notice that his BP can be increased much higher then before.
     4. A) As mentioned in the description, this effect is amplified greatly with ascended BPMs. For example: when you first fuse, the fusion character will not have an ascended BPM. Repeat step 3 before it ascends. After it ascends, adjust the BP of the dominant fusee once again. Once you defuse you'll be able to have all of that BP as your base after defusing.

**Expected behavior**

Obviously I shouldn't be able to take the relative BP of the fusion entity and stick it onto the regular character, and I think it may aid in the cause of why fusion after BPM ascension seems to amplify server gains more than they should. My personal solution would be to have fusions break any soul contract the fusees are attached to, since there is no other issue with soul contract that involves any similar methods.

**Screenshots**

**Byond Details:**
- Version (ex. 512, 513, etc):

I doubt the version matters. My test partner and I were running different versions, both public and beta.

**First identifiable version:**
What is the earliest version of the game in which you found this bug to exist?

I'm pretty sure this can be done ever since the fusion update's release.

**Comment by Khunkurisu** [comment]
It should now be impossible to interact with a soul while fused, or to interact with a fused soul.
