### ISSUE TITLE
[Suggestion] Majin Overhaul

### ISSUE THREAD

**Issue by CheesyShaft** [DU-Devs/Dragon-Universe-Public#79]
**Is your feature request related to a problem? Please describe.**
The issue with Majins is that they are simply too basic. The Majin Buu in the show was changing constantly in appearance and power, meanwhile Majins in this game are just quickly regenerating carnivores that never change.
**Describe the solution you'd like**
The idea I had that could improve this would be for Absorption to be changed to make Majin gameplay more interesting. Instead of simply killing the victim by using it on them when they are knocked out, it could function similarly to the special goo but instead of just killing them it will take them into your body and they will enter an internal body area not unlike where Goku and Vegeta went after they were absorbed by Buuhan. The idea would be that it would drain your health not unlike the core of Braal where if you do not defeat a Majin NPC (Or something to that end) with the same power and stats of the one who absorbed you, the "smog" damage will digest you, permanently adding the power boost to the Majin, but if they manage to fight their way out, they would escape and the Majin would lose the boost. If multiple people were absorbed or for example a fusion was absorbed that split up they could work together to kill the Majin NPC and escape together or both perish allowing two gains at once. In order to balance the absorption from massive boosts from fusions, they would split as soon as they enter. Additionally, to balance the absorption method it could only be used on those who are too weak to resist not unlike the special goo currently does. An optional cosmetic update to make the Majins themselves more interesting could be they get some item of clothing in relation to either who they absorbed (if even possible) or simply what race they were ie: saiyan armor for saiyans, cape for nameks, turtle gi for humans, etc. The method for escaping after the npc is defeated could be a portal that opens up for a few moments before closing again.
**Describe alternatives you've considered**
If this idea is not realistically possible, just some kind of physical change for majins as they absorb people would also be nice, its a shame to see such a cool villain in the show represented by an unchanging race with no forms to their name. Of course, if you have some idea for majins outside what I suggested I think any development on them would be nice.
**Additional context**
![maxresdefaultff](https://user-images.githubusercontent.com/71481449/93556182-2579fd00-f946-11ea-99f9-cd516c641d35.jpg)

Attached is the image of the inside buu stage from Dragon Ball Infinite, it could be as simple as just a veiny pink area (If you can't see the imagine DM me at The Cheesiest Shafter#4364 on Discord)

**Comment by Khunkurisu** [comment]
You've pretty much described a similar overhaul to the one I was already working on for Majins.  It has since been put on indefinite hiatus due to lack of time and funding, much like most of the game's possible feature additions.
