### ISSUE TITLE
[BUG] Randomly losing connection (all players)

### ISSUE THREAD

**Issue by N3nr1k1** [DU-Devs/Dragon-Universe-Public#80]
**Describe the bug**
When running a server through Dream Daemon the connection randomly closes after some time passes for all players. This has happened when hosting through different PCs. There are no error messages or warnings to indicate why the connection is lost in Dream Seeker or Daemon. 

I have however found some errors in the Errors.log, though unsure whether this is what causes the connection to be lost:

`runtime error: upForm assertion: FormInitTempVars() must be implemented when handling forms
proc name: FormInitTempVars (/upForm/proc/FormInitTempVars)
  usr: Nenriki (/mob)
  src: /upForm/admin_panel (/upForm/admin_panel)
  usr.loc: GroundDirt (415,89,4) (/turf/GroundDirt)
  call stack:
/upForm/admin_panel (/upForm/admin_panel): FormInitTempVars()
/upForm/admin_panel (/upForm/admin_panel): InitSettings()
/upForm/admin_panel (/upForm/admin_panel): New(Nenriki (/client), Nenriki (/mob), /list (/list))
upForm(Nenriki (/client), Nenriki (/mob), /upForm/admin_panel (/upForm/admin_panel), null)
Nenriki (/mob): ServerSettings()
Nenriki (/mob): Server Control Panel()
runtime error: upForm assertion: FormInitTempVars() must be implemented when handling forms
proc name: FormInitTempVars (/upForm/proc/FormInitTempVars)
  usr: Nenriki (/mob)
  src: /upForm/admin_panel (/upForm/admin_panel)
  usr.loc: GroundDirt (415,89,4) (/turf/GroundDirt)
  call stack:
/upForm/admin_panel (/upForm/admin_panel): FormInitTempVars()
/upForm/admin_panel (/upForm/admin_panel): InitSettings()
/upForm/admin_panel (/upForm/admin_panel): New(Nenriki (/client), Nenriki (/mob), /list (/list))
upForm(Nenriki (/client), Nenriki (/mob), /upForm/admin_panel (/upForm/admin_panel), null)
/upForm/admin_world (/upForm/admin_world): FormSubmitSuccess("admin", Nenriki (/client))
/upForm/admin_world (/upForm/admin_world): HandleFormLinks(/list (/list), Nenriki (/client))
/upForm/admin_world (/upForm/admin_world): Topic("src=%5B0x21000023%5D&form=admi...", /list (/list))
Nenriki (/client): Topic("src=%5B0x21000023%5D&form=admi...", /list (/list), /upForm/admin_world (/upForm/admin_world))
runtime error: upForm assertion: FormInitTempVars() must be implemented when handling forms
proc name: FormInitTempVars (/upForm/proc/FormInitTempVars)
  usr: Nenriki (/mob)
  src: /upForm/admin_panel (/upForm/admin_panel)
  usr.loc: Grass12 (208,65,4) (/turf/Grass12)
  call stack:
/upForm/admin_panel (/upForm/admin_panel): FormInitTempVars()
/upForm/admin_panel (/upForm/admin_panel): InitSettings()
/upForm/admin_panel (/upForm/admin_panel): New(Nenriki (/client), Nenriki (/mob), /list (/list))
upForm(Nenriki (/client), Nenriki (/mob), /upForm/admin_panel (/upForm/admin_panel), null)
Nenriki (/mob): ServerSettings()
Nenriki (/mob): Server Control Panel()
runtime error: upForm assertion: FormInitTempVars() must be implemented when handling forms
proc name: FormInitTempVars (/upForm/proc/FormInitTempVars)
  usr: Nenriki (/mob)
  src: /upForm/admin_panel (/upForm/admin_panel)
  usr.loc: Grass12 (208,65,4) (/turf/Grass12)
  call stack:
/upForm/admin_panel (/upForm/admin_panel): FormInitTempVars()
/upForm/admin_panel (/upForm/admin_panel): InitSettings()
/upForm/admin_panel (/upForm/admin_panel): New(Nenriki (/client), Nenriki (/mob), /list (/list))
upForm(Nenriki (/client), Nenriki (/mob), /upForm/admin_panel (/upForm/admin_panel), null)
/upForm/admin_world (/upForm/admin_world): Link(/list (/list), Nenriki (/client))
/upForm/admin_world (/upForm/admin_world): Topic("src=\[0x2100002a]&action=menu", /list (/list))
Nenriki (/client): Topic("src=\[0x2100002a]&action=menu", /list (/list), /upForm/admin_world (/upForm/admin_world))
Ban server failed to connect.
runtime error: upForm assertion: FormInitTempVars() must be implemented when handling forms
proc name: FormInitTempVars (/upForm/proc/FormInitTempVars)
  usr: Nenriki (/mob)
  src: /upForm/admin_panel (/upForm/admin_panel)
  usr.loc: Grass12 (208,65,4) (/turf/Grass12)
  call stack:
/upForm/admin_panel (/upForm/admin_panel): FormInitTempVars()
/upForm/admin_panel (/upForm/admin_panel): InitSettings()
/upForm/admin_panel (/upForm/admin_panel): New(Nenriki (/client), Nenriki (/mob), /list (/list))
upForm(Nenriki (/client), Nenriki (/mob), /upForm/admin_panel (/upForm/admin_panel), null)
/upForm/admin_gains (/upForm/admin_gains): FormSubmitSuccess("admin", Nenriki (/client))
/upForm/admin_gains (/upForm/admin_gains): HandleFormLinks(/list (/list), Nenriki (/client))
/upForm/admin_gains (/upForm/admin_gains): Topic("src=%5B0x2100002a%5D&form=admi...", /list (/list))
Nenriki (/client): Topic("src=%5B0x2100002a%5D&form=admi...", /list (/list), /upForm/admin_gains (/upForm/admin_gains))
Ban server failed to connect.
runtime error: upForm assertion: FormInitTempVars() must be implemented when handling forms
proc name: FormInitTempVars (/upForm/proc/FormInitTempVars)
  usr: Nenriki (/mob)
  src: /upForm/admin_panel (/upForm/admin_panel)
  usr.loc: Planet Vegeta Fitness (110,6,4) (/turf/Tile6)
  call stack:
/upForm/admin_panel (/upForm/admin_panel): FormInitTempVars()
/upForm/admin_panel (/upForm/admin_panel): InitSettings()
/upForm/admin_panel (/upForm/admin_panel): New(Nenriki (/client), Nenriki (/mob), /list (/list))
upForm(Nenriki (/client), Nenriki (/mob), /upForm/admin_panel (/upForm/admin_panel), null)
Nenriki (/mob): ServerSettings()
Nenriki (/mob): Server Control Panel()
runtime error: upForm assertion: FormInitTempVars() must be implemented when handling forms
proc name: FormInitTempVars (/upForm/proc/FormInitTempVars)
  usr: Nenriki (/mob)
  src: /upForm/admin_panel (/upForm/admin_panel)
  usr.loc: Planet Vegeta Fitness (110,6,4) (/turf/Tile6)
  call stack:
/upForm/admin_panel (/upForm/admin_panel): FormInitTempVars()
/upForm/admin_panel (/upForm/admin_panel): InitSettings()
/upForm/admin_panel (/upForm/admin_panel): New(Nenriki (/client), Nenriki (/mob), /list (/list))
upForm(Nenriki (/client), Nenriki (/mob), /upForm/admin_panel (/upForm/admin_panel), null)
/upForm/admin_world (/upForm/admin_world): Link(/list (/list), Nenriki (/client))
/upForm/admin_world (/upForm/admin_world): Topic("src=\[0x21000025]&action=menu", /list (/list))
Nenriki (/client): Topic("src=\[0x21000025]&action=menu", /list (/list), /upForm/admin_world (/upForm/admin_world))
Ban server failed to connect.`

**To Reproduce**
1. Start a server via Dream Daemon in either Private or Invisible.
2. Login and wait for connection to be lost.

**Expected behavior**
That the connection isn't randomly lost.

**Screenshots**

**Byond Details:**
5.0 Public - Version 513.1541

**First identifiable version:**
v35.5.1

**Comment by IzekaiYagami** [comment]
I'm getting this problem too.. Have you found a fix for it yet?

**Comment by Khunkurisu** [comment]
Problem is due to the backend system being down.  I finally managed to release a stable version that doesn't crash itself like this.  (That said, this behavior *was* intentional previously.)
