### ISSUE TITLE
Hi Khun, please help me?

### ISSUE THREAD

**Issue by KevCore** [DU-Devs/Dragon-Universe-Public#82]
Hi Khun, I can't play as a guest, because I'm currently banned from Byond, I can only play as a guest. In addition, I'm unfortunately still banned on your Discord and that's why I'm writing here. Can you possibly allow guest accounts to play along?

I always wanted to excuse myself for my behavior towards you and I hope that you will accept this one day?

I would be happy to join your Discord again and hope you will allow me to do so again.

Sincerely, KevCore

**Comment by Khunkurisu** [comment]
You've been given multiple chances only to get yourself banned over and over again.  If you can't play because you got banned, that's not my problem to handle mate.  Servers choose whether to allow guests.
