### ISSUE TITLE
[BUG] Player crashes if Splitform is used while fused and then the player unfuses without dismissing the skill

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#85]
**Describe the bug**
If a fused player uses Splitform and then unfuses after it, he crashes. Only the controlling player (the one who used Splitform) crashes; nothing happens to the other player who was fused. In this case, I use crashing to refer to a frozen game with only a "Connection died" error appearing at chat.

With the crash, the Splitform disappears.

1. Fuse with someone.
2. Use splitform.
3. Defuse.
4. See "connection died" alert at chat.

**Expected behavior**
The Splitform should disappear without the player crashing.

**Screenshots**
Full game screenshot:
![unknown](https://user-images.githubusercontent.com/81521485/112757157-ea284d00-8fbe-11eb-9370-69e7a6efc51b.png)
F1 console screenshot:
![image](https://user-images.githubusercontent.com/81521485/112757170-fd3b1d00-8fbe-11eb-86bc-ea0fa26a7d48.png)

**Byond Details:**
Any.

**First identifiable version:**
The version the bug was detected was the March 4th, 2021 (2021-03-04) release, named "Dragon Universe Classic r20210304", but it may also be present since the first fusion update (the beta from 2020.07.06).

**Comment by Khunkurisu** [comment]
Defusing should now delete all active splitforms of the Fused character first.
