### ISSUE TITLE
[BUG] Player crashes if Final Explosion is charged while fused and then the player unfuses without using the skill

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#86]
**Describe the bug**
If a fused player charges Final Explosionand then unfuses without using it, he crashes. Only the controlling player (the one who used Splitform) crashes; nothing happens to the other player who was fused. In this case, I use crashing to refer to a frozen game with only a "Connection died" error appearing at chat. 
The Final Explosion sprite also stays at the map after the player is unfused.

**To Reproduce**
1. Fuse with someone.
2. Charge the skill Final Explosion.
3. Defuse.
4. See "connection died" alert at chat.

**Expected behavior**
The skill should be cancelled or the player should be unable to unfuse while the skill is being used.

**Screenshots**
N/A.

**Byond Details:**
Any.

**First identifiable version:**
The version the bug was detected was the March 4th, 2021 (2021-03-04) release, named "Dragon Universe Classic r20210304", but it may also be present since the first fusion update (the beta from 2020.07.06).

**Comment by Khunkurisu** [comment]
Fused characters can no longer use Final Explosion for the time being.  In order for it to function in a balanced way (and fix underlying issues like this one) it will need rewritten.  For now, this solves the issue.
