### ISSUE TITLE
[BUG] Game reacts strangely when players unfuse while using skills

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#87]
**Describe the bug**
If a fused player uses a skill that has a period of charge and automatic release (sokidan and kienzan) and unfuses before it is released, the skill will bug on the map. It also works on skills that have no automatic release like Death ball and beams are exempt from it.

For example, a Kienzan will stay in place and will only disappear when someone touches it (it does no damage, however) or the game reboots.

**To Reproduce**
1. Fuse with someone.
2. Use a skill with charging and auto-release like Kienzan.
3. Unfuse before it is released.
4. See the skill icon bug on the map.

**Expected behavior**
The skill should be cancelled or the player should be unable to unfuse while the skill is being used.

**Screenshots**
Screenshot from game:
![image](https://user-images.githubusercontent.com/81521485/112758436-c6680580-8fc4-11eb-8277-1c01118073e7.png)

(the two players were fused, with the top-left one being the one who used the skill)

**Byond Details:**
Any.

**First identifiable version:**
The version the bug was detected was the March 4th, 2021 (2021-03-04) release, named "Dragon Universe Classic r20210304", but it may also be present since the first fusion update (the beta from 2020.07.06).

**Comment by Khunkurisu** [comment]
Blasts and other ki abilities should now properly disperse if their owner (such as a fused character) no longer exists, logs out, defuses, etc.
