### ISSUE TITLE
[BUG] Player screen colors get stuck on Dropkick effects if the target of the skills fuse with someone before getting hit

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#88]
**Describe the bug**
The screen colors of the player who used the Dropkick skill does not return to normal if the player who was targeted fuses with someone with Potara fusion. The skill attacks no one after the fusion is done.

**To Reproduce**
1. Use Dropkick on someone.
2. That someone will fuse with another player.
3. The screen colors of the attacker will get stuck with the Dropkick effect.

**Expected behavior**
The skill should get cancelled when the target fuses (or the target should be unable to fuse while being targeted). 

**Screenshots**
Screenshot from game:
![image](https://user-images.githubusercontent.com/81521485/112758644-c3214980-8fc5-11eb-95aa-e73e21475f57.png)

**Byond Details:**
Any.

**First identifiable version:**
The version the bug was detected was the March 4th, 2021 (2021-03-04) release, named "Dragon Universe Classic r20210304", but it may also be present since the first fusion update (the beta from 2020.07.06).

**Comment by Khunkurisu** [comment]
Dropkick has been removed from the game, so this issue is no longer relevant.
