### ISSUE TITLE
[BUG] You can dropkick someone and fuse with that person at the same time

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#89]
**Describe the bug**
It is possible to throw a Potara to someone and then use the Dropkick skill on that person who can accept the fusion and the skill will get canceled (it also bugs the screen colors like issue #88 but only for the one who used dropkick).

**To Reproduce**
1. Throw a Potara to someone.
2. Use dropkick on that person.
3. That person will then accept the fusion and you will fuse mid-dropkick.

**Expected behavior**
You should not be able to fuse mid-skill (or you should not be able to use skills after throwing a Potara).

**Screenshots**
N/A

**Byond Details:**
Any.

**First identifiable version:**
The version the bug was detected was the March 4th, 2021 (2021-03-04) release, named "Dragon Universe Classic r20210304", but it may also be present since the first fusion update (the beta from 2020.07.06).

**Comment by Khunkurisu** [comment]
It should no longer be possible to fuse while lunging, using drop kick, charging an attack, etc.  If any of these cases slip through the cracks please report as a new issue.
