### ISSUE TITLE
[SUGGESTION] Dash Attack damage needs rebalanced

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#90]
**Describe the bug**
The skill Dash Attack does an unreasonable amount of damage. It can one-hit-KO a LSSJ with 500m BP by an alien player with no extra points on STR (using the default 0.8 points) and that has only 16m BP (more than thirty times less than the other player). It works with other races as well.
 
The side of the person getting hit does not matter. Even a frontal attack does the same damage.

**To Reproduce**
1. Get someone that you should NOT be able to insta KO with any skill.
2. Use dash attack on that person.
3. Immediately KO that person.

**Expected behavior**
You should not be able to instantly KO someone with the Dash Attack skill if there is such a huge difference of BP (and stats). While it is somewhat fine to be able to insta-anger someone with an attack hitting the person's back, a frontal attack doing the same is no good.

**Screenshots**
N/A.

**Byond Details:**
Any.

**First identifiable version:**
The version the bug was detected was the March 4th, 2021 (2021-03-04) release, named "Dragon Universe Classic r20210304".

**Comment by Khunkurisu** [comment]
This is not a bug, but rather a balance issue.  I'll look into it, but in the future be sure to choose the proper option when reporting an issue.  In this case it would be better handled as a suggestion to rebalance the skill.

**Comment by Khunkurisu** [comment]
Dash attack damage is now capped.  Should still be incredibly powerful if you hit, but no longer beyond reason.
