### ISSUE TITLE
[BUG] A fused Icer has no icon if it changes form

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#91]
**Describe the bug**
If two icers fuse they have no icon on forms other than the first.

**To Reproduce**
1. Fuse with another icer.
2. Change forms.
3. See that your icon is now invisible.

**Expected behavior**
You should have default icons for an Icer.

**Screenshots**
N/A 

**Byond Details:**
Any.

**First identifiable version:**
The version the bug was detected was the March 4th, 2021 (2021-03-04) release, named "Dragon Universe Classic r20210304", but it may also be present since the first fusion update (the beta from 2020.07.06).

**Comment by Khunkurisu** [comment]
Upcoming minor patch should see this issue resolved.
