### ISSUE TITLE
[Suggestion] Change how "Stream music to everyone nearby" works

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#92]
**Is your feature request related to a problem? Please describe.**
Yes. The current verb 'Stream-music-to-everyone-nearby" does not work with the Vocaroo.com domain. It only accepts old.vocaroo ones, but now all old.vocaroo links redirect to Vocaroo.com.

**Describe the solution you'd like**
Either the game accept Vocaroo.com links if possible or simply remove the verb from the game since it is useless (or change it to use another sort of site).

**Describe alternatives you've considered**
N/A.

**Additional context**
Vocaroo.com updated all links sometime last year so Old.vocaroo redirects to its new version and the game *seems* to filter requests to "old.vocaroo" so they don't work anymore.

**Comment by Khunkurisu** [comment]
Disabled, at least for now.  Never much cared for it anyways.
