### ISSUE TITLE
[BUG] If two Saiyajins with the requeriments to turn into one fuse and the fusion gets angered, they can go straight to SSJ3

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#93]
**Describe the bug**
If two Saiyajins who have the requeriments to turn into SSJ1 but didn't turn yet, the fusion resulted from then will be able to get SSJ1 when angered and then will be able to turn into SSJ2 and SSJ3. It isn't really necessary for it to be **two** Saiyans, only the main one needs to be from that race. 

The transformations also have a direct influence into the game knowledge cap since the Super Saiyan transformations increasce relative BP (at least from what I could infer).

Note: the saiyans **DO NOT** need to be a super saiyan. They only need the **REQUERIMENTS**. If the fusion has the **REQUERIMENTS**, the issue described above happens. It wasn't tested with proper Super Saiyans but it *probably* does not happens. Also, when the Saiyans unfuse they do not keep the ability to go into Super Saiyan.

**To Reproduce**
1. Have a Saiyajin with *only* the requeriments to **SSJ1** fuse if someone else with that Saiyan being the main part.
2. Anger that Saiyan. 
3. Watch as the Saiyan turns into SSJ1.
4. Watch, again, as the Saiyan goes straight into SSJ2 and then SSJ3 if he powers up again.
5. Watch, once more, as the Knowledge Cap breaks due to the transformations.

**Expected behavior**
The fusion should not be able to jump eras to go straight into SSJ3. And the transformation should (hopefully) not advance the current knowledge cap.

**Screenshots**
N/A

**Byond Details:**
Any.

**First identifiable version:**
The version the bug was detected was the March 4th, 2021 (2021-03-04) release, named "Dragon Universe Classic r20210304", but it may also be present since the first fusion update (the beta from 2020.07.06).

**Comment by Khunkurisu** [comment]
While the way it manifests is certainly odd in-game, fusions being able to reach SSj3 if they have SSj unlocked is intended.  I may in the future make it more apparent, but for now I'm marking this as closed as it isn't actually a bug.
