### ISSUE TITLE
[BUG] If you die with as a Fused Character and unfuses after it, you unfuse alive

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#94]
**Describe the bug**
Fused players who died unfuse alive.

**To Reproduce**
1. Fuse with someone.
2. Die.
3. Unfuse.
4. See both players alive.

**Expected behavior**
The players should die.

**Screenshots**
N/A

**Byond Details:**
Any.

**First identifiable version:**
The version the bug was detected was the March 4th, 2021 (2021-03-04) release, named "Dragon Universe Classic r20210304", but it may also be present since the first fusion update (the beta from 2020.07.06).

**Comment by Khunkurisu** [comment]
A dead fusion should now result in two dead players when the fusion ends.
