### ISSUE TITLE
[BUG] If two players have active buffs and they fuse, both buffs will stay active on the fusion

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#96]
**Describe the bug**
See title.

**To Reproduce**
1. Get two players and make then activate buffs.
2. Make them fuse.
3. See that both buffs are influencing the fused character.

**Expected behavior**
The buffs should be disabled on the fused character. 

**Screenshots**
One of the buffs is maxed on Durability (without removing Resistance) and the other on Resisstance (without removing Durability).
Stats screen with both buffs applied
![image](https://user-images.githubusercontent.com/81521485/112761503-008bd400-8fd2-11eb-866b-9bd81fe7618f.png)
Chat logs for the buffs being disabled: 
![image](https://user-images.githubusercontent.com/81521485/112761516-0bdeff80-8fd2-11eb-8ae2-de9b6323c56c.png)S
Stats screen with both buffs disabled:
![image](https://user-images.githubusercontent.com/81521485/112761537-1b5e4880-8fd2-11eb-8535-665be5470ad3.png)

**Byond Details:**
Any.

**First identifiable version:**
The version the bug was detected was the March 4th, 2021 (2021-03-04) release, named "Dragon Universe Classic r20210304", but it may also be present since the first fusion update (the beta from 2020.07.06).

**Comment by Khunkurisu** [comment]
Entering a fusion should now disable any active buffs on both fusees.
