### ISSUE TITLE
[BUG] Game seems to halt working randomly if there are fused players

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#98]
**Describe the bug**
The game randomly freezes for 10 to 20 seconds if there is a fused player. While I can't be certain about it, fused players should probably the cause. Yesterday, while some testing was being done, there were fused players and the game would halt working for seemingly no reason. Today, while there are *no* fused players, the game didn't halt even once so it should be at least related.

**To Reproduce**
1. Get some players to fuse.
2. Keep playing and see the game freeze randomly.

**Expected behavior**
The game should *not* halt working if there are fused players.

**Screenshots**
N/A.

**Byond Details:**
The BYOND version of the host was 513.1542.

**First identifiable version:**
The version the bug was detected was the March 4th, 2021 (2021-03-04) release, named "Dragon Universe Classic r20210304".

**Comment by Kaseioo** [comment]
Sorry for not being clear enought. (Or using bad terms/explanations).

Basically, this issue was opened based on the line of thought that having fused players online at any time would make the entire game stop responding for no reason other than a player being fused.

I can't really think of a explanation bether than that (probably I'm being really dumb with it tho).

However, after playing for a few more days, I think the issue can be somewhat narrowed down further. The problem does not seem to be directly related to fusions, but instead to Alts or having someone with Admin 4 logged in.

While those reasons are somewhat a strech, they are the only things in common when related to the random freezes. Whenever a player had an alt logged in or someone with Admin 4 entered the game, the game would simply stop responding for a few seconds. 

It may be something completely unrelated to all of this, but this is the best guess I can do for now. I will try my best to give more info related to this issue if possible.

**Comment by Khunkurisu** [comment]
See my comment on #104.

**Comment by Khunkurisu** [comment]
This issue seems to be resolved.
