### ISSUE TITLE
[Suggestion] Make it so the default font for All/OOC/IC tabs in chat are equal

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#99]
**Is your feature request related to a problem? Please describe.**
Yes. The font for the OOC and IC tabs in chat seems to be different from the one that All uses. The font size also seems to be different, but I can't really be certain about this one,

**Describe the solution you'd like**
The default font for all Chat tabs should be the same. Otherwise, the player should be able to change the font (if possible).

**Describe alternatives you've considered**
N/A.

**Additional context**
N/A.

**Comment by Khunkurisu** [comment]
Resolved
